# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="epymetheus"
REALVERSION="0.17.1"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Multi-asset Backtesting Framework"

HOMEPAGE="https://github.com/epymetheus/epymetheus"
LICENSE="BSD"
SRC_URI="https://files.pythonhosted.org/packages/source/e/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/numpy[${PYTHON_USEDEP}]
	dev-python/pandas[${PYTHON_USEDEP}]
	dev-python/pandas-datareader[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
