# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="0.0.1a4"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Dash wrapper for Plotly's react-chart-editor"

HOMEPAGE="https://github.com/BSd3v/dash-chart-editor"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/4a/b2/aca0092e4008335a21d255e19944939a4b3a134338f7c30143e669c849f3/dash_chart_editor-${REALVERSION}.tar.gz"
SOURCEFILE="dash_chart_editor-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=""
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
