# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="The aim of this project is to provide a python library for patching ELF binary file. It only supports for the moment x86 and x86_64 architecture."

HOMEPAGE="https://github.com/0xswitch/Hellf"
LICENSE="WTFPL-2"
SRC_URI="https://files.pythonhosted.org/packages/5a/93/855e305636d45b73844ab90ca86900e1d19730623ea40c13a243f508c3f8/Hellf-${REALVERSION}.tar.gz"
SOURCEFILE="Hellf-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=""
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
