# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Telegram Bot for reposting from VK"

HOMEPAGE="https://github.com/qwertyadrian/TG_AutoPoster"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/1f/76/a949777697d39bb493777b7945d412dde2ae526f2753f7d05af7bc7dd2ee/TG_AutoPoster-${REALVERSION}.tar.gz"
SOURCEFILE="TG_AutoPoster-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/vk-api[${PYTHON_USEDEP}]
	dev-python/pyrogram[${PYTHON_USEDEP}]
	dev-python/tgcrypto[${PYTHON_USEDEP}]
	dev-python/loguru[${PYTHON_USEDEP}]
	dev-python/wget[${PYTHON_USEDEP}]
	dev-python/mutagen[${PYTHON_USEDEP}]
	dev-python/beautifulsoup4[${PYTHON_USEDEP}]
	dev-python/apscheduler[${PYTHON_USEDEP}]
	dev-python/PyYAML[${PYTHON_USEDEP}]
	dev-python/m3u8[${PYTHON_USEDEP}]
	dev-python/pycryptodome[${PYTHON_USEDEP}]
	dev-python/moviepy[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
