# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Bash colors management and log system"

HOMEPAGE="https://github.com/OlivierB/Bashutils.git"
LICENSE="GPL-3"
SRC_URI="https://files.pythonhosted.org/packages/a0/53/a35356e2eaeced6fc15c10c71397b731d5f37e00b1e44a6eb4437d171277/Bashutils-${REALVERSION}.tar.gz"
SOURCEFILE="Bashutils-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=""
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
