# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Making Django REST Framework reactive"

HOMEPAGE="https://github.com/genialis/django-rest-framework-reactive"
LICENSE="Apache-2.0"
SRC_URI="https://files.pythonhosted.org/packages/source/d/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="docs package test"
DEPENDENCIES="dev-python/Django[${PYTHON_USEDEP}]
	dev-python/djangorestframework[${PYTHON_USEDEP}]
	dev-python/channels[${PYTHON_USEDEP}]
	docs? ( dev-python/sphinx[${PYTHON_USEDEP}] )
	docs? ( dev-python/sphinx-rtd-theme[${PYTHON_USEDEP}] )
	package? ( dev-python/twine[${PYTHON_USEDEP}] )
	package? ( dev-python/wheel[${PYTHON_USEDEP}] )
	test? ( dev-python/django-filter[${PYTHON_USEDEP}] )
	test? ( dev-python/django-guardian[${PYTHON_USEDEP}] )
	test? ( dev-python/django-priority-batch[${PYTHON_USEDEP}] )
	test? ( dev-python/channels-redis[${PYTHON_USEDEP}] )
	test? ( dev-python/pytest[${PYTHON_USEDEP}] )
	test? ( dev-python/pytest-django[${PYTHON_USEDEP}] )
	test? ( dev-python/pytest-asyncio[${PYTHON_USEDEP}] )
	test? ( dev-python/async-timeout[${PYTHON_USEDEP}] )
	test? ( dev-python/psycopg2-binary[${PYTHON_USEDEP}] )
	test? ( dev-python/check-manifest[${PYTHON_USEDEP}] )
	test? ( dev-python/twine[${PYTHON_USEDEP}] )
	test? ( dev-python/setuptools-scm[${PYTHON_USEDEP}] )
	test? ( dev-python/black[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
