# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Markerless pose-estimation of user-defined features with deep learning"

HOMEPAGE="https://github.com/DeepLabCut/DeepLabCut"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="apple_mchips docs gui modelzoo openvino tf"
DEPENDENCIES="dev-python/dlclibrary[${PYTHON_USEDEP}]
	dev-python/filterpy[${PYTHON_USEDEP}]
	>=dev-python/ruamel-yaml-0.15.0[${PYTHON_USEDEP}]
	dev-python/imgaug[${PYTHON_USEDEP}]
	dev-python/imageio-ffmpeg[${PYTHON_USEDEP}]
	dev-python/numba[${PYTHON_USEDEP}]
	>=dev-python/matplotlib-3.3[${PYTHON_USEDEP}]
	>=dev-python/networkx-2.6[${PYTHON_USEDEP}]
	>=dev-python/numpy-1.18.5[${PYTHON_USEDEP}]
	>=dev-python/pandas-1.0.1[${PYTHON_USEDEP}]
	>=dev-python/scikit-image-0.17[${PYTHON_USEDEP}]
	>=dev-python/scikit-learn-1.0[${PYTHON_USEDEP}]
	>=dev-python/scipy-1.9[${PYTHON_USEDEP}]
	>=dev-python/statsmodels-0.11[${PYTHON_USEDEP}]
	>=dev-python/tables-3.7.0[${PYTHON_USEDEP}]
	dev-python/torch[${PYTHON_USEDEP}]
	dev-python/tensorpack[${PYTHON_USEDEP}]
	dev-python/tf-slim[${PYTHON_USEDEP}]
	dev-python/tqdm[${PYTHON_USEDEP}]
	dev-python/pyyaml[${PYTHON_USEDEP}]
	>=dev-python/pillow-7.1[${PYTHON_USEDEP}]
	apple_mchips? ( dev-python/tensorflow-macos[${PYTHON_USEDEP}] )
	apple_mchips? ( dev-python/tensorflow-metal[${PYTHON_USEDEP}] )
	docs? ( dev-python/numpydoc[${PYTHON_USEDEP}] )
	gui? ( <dev-python/pyside6-6.3.2[${PYTHON_USEDEP}] )
	gui? ( ~dev-python/qdarkstyle-3.1[${PYTHON_USEDEP}] )
	gui? ( dev-python/napari-deeplabcut[${PYTHON_USEDEP}] )
	modelzoo? ( dev-python/huggingface-hub[${PYTHON_USEDEP}] )
	openvino? ( dev-python/openvino-dev[${PYTHON_USEDEP}] )
	tf? ( dev-python/tensorflow[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
