# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="The modern realtime feature engineering platform"

HOMEPAGE=""
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/d3/a8/7f8c8d744e79445c98a4d21d21682e90be7ed8f540db6f7dc29921d2b2ac/fennel_ai-${REALVERSION}.tar.gz"
SOURCEFILE="fennel_ai-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/pandas[${PYTHON_USEDEP}]
	dev-python/protobuf[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
