# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12} )
DISTUTILS_USE_PEP517=wheel

inherit python-r1 gs-pypi

DESCRIPTION="This library contains Cybotrade's core runtime, integrations with Exchanges API, historical and live market data collector and wrap them into a simple, easy-to-use Python SDK. [wheel]"

HOMEPAGE="https://app.cybotrade.rs"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/45/8c/86286913b83abde465bf47b78f9781f890993e429315edcb2c7d382e38bb/${REALNAME}-${REALVERSION}-1-cp311-none-win_amd64.whl"
SOURCEFILE="${REALNAME}-${REALVERSION}-1-cp311-none-win_amd64.whl"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="virtual/allow-pypi-wheels"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
