# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Beergarden Application"

HOMEPAGE="https://beer-garden.io"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="<dev-python/apispec-0.39[${PYTHON_USEDEP}]
	<dev-python/APScheduler-4.0[${PYTHON_USEDEP}]
	>=dev-python/python-box-3.3.0[${PYTHON_USEDEP}]
	dev-python/brewtils[${PYTHON_USEDEP}]
	<dev-python/marshmallow-3.0[${PYTHON_USEDEP}]
	dev-python/mongoengine[${PYTHON_USEDEP}]
	<dev-python/more-itertools-9.0[${PYTHON_USEDEP}]
	dev-python/motor[${PYTHON_USEDEP}]
	<dev-python/passlib-1.8[${PYTHON_USEDEP}]
	<dev-python/prometheus-client-1.0[${PYTHON_USEDEP}]
	<dev-python/pyyaml-5.4[${PYTHON_USEDEP}]
	dev-python/pyrabbit2[${PYTHON_USEDEP}]
	<dev-python/pytz-2021.0[${PYTHON_USEDEP}]
	>=dev-python/pyjwt-2.4.0[${PYTHON_USEDEP}]
	<dev-python/ruamel-yaml-0.17[${PYTHON_USEDEP}]
	<dev-python/stomp-py-6.2.0[${PYTHON_USEDEP}]
	<dev-python/tornado-7.0[${PYTHON_USEDEP}]
	<dev-python/urllib3-2.0[${PYTHON_USEDEP}]
	>dev-python/watchdog-2.1.0[${PYTHON_USEDEP}]
	<=dev-python/wrapt-1.15.0[${PYTHON_USEDEP}]
	dev-python/yapconf[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
