# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Python module for xml parse"

HOMEPAGE=""
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/e8/40/97b9a9d1f6991fe57c2fe14d48157f51a0724cb0ec0f4fd33053cf6e5fa3/xmlApiParse-${REALVERSION}.tar.gz"
SOURCEFILE="xmlApiParse-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=""
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
