# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="sceptre-file-resolver"
REALVERSION="1.0.6"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
REPO_URI="http://pypi.python.org/packages/source/${REALNAME:0:1}/${REALNAME}/"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
DISTUTILS_USE_PEP517=standalone

inherit gs-pypi

DESCRIPTION="A Sceptre resolver to retrieve file content"

HOMEPAGE="https://github.com/sceptre/sceptre-file-resolver"
LICENSE="Apache2"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="test"
DEPENDENCIES="dev-python/requests[${PYTHON_USEDEP}]
	dev-python/sceptre[${PYTHON_USEDEP}]
	test? ( dev-python/pytest[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
