# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="TheSilent is a fast subdomain enumeration tool!"

HOMEPAGE="https://github.com/Invizabel/The-Silent"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/9f/16/03c7c1760ea880cbcf6e0482134fd9ef4a9a118b4e15ca6959f0467ad587/thesilent-${REALVERSION}.tar.gz"
SOURCEFILE="thesilent-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=""
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
