# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="opentelemetry-instrumentation-flask"
REALVERSION="0.38b0"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Flask instrumentation for OpenTelemetry"

HOMEPAGE="https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-flask"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/13/d6/fb1f8a65db94e0e7a127004e9fd2a7538463f9473262d81d1270bc120e8e/opentelemetry_instrumentation_flask-${REALVERSION}.tar.gz"
SOURCEFILE="opentelemetry_instrumentation_flask-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="instruments test"
DEPENDENCIES="dev-python/opentelemetry-api[${PYTHON_USEDEP}]
	dev-python/opentelemetry-instrumentation-wsgi[${PYTHON_USEDEP}]
	dev-python/opentelemetry-instrumentation[${PYTHON_USEDEP}]
	dev-python/opentelemetry-semantic-conventions[${PYTHON_USEDEP}]
	dev-python/opentelemetry-util-http[${PYTHON_USEDEP}]
	instruments? ( dev-python/flask[${PYTHON_USEDEP}] )
	test? ( dev-python/markupsafe[${PYTHON_USEDEP}] )
	test? ( dev-python/opentelemetry-instrumentation-flask[${PYTHON_USEDEP}] )
	test? ( dev-python/opentelemetry-test-utils[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
