# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Dynamic graph embedding algorithm (DGEA) to gradually shift the projection of modified vertices"

HOMEPAGE="https://github.com/AmitKabya/FODGE"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/99/dd/4cd09294c5eec6d622756e2df8a38be43c77cffbc9b9eb92e0341a9bfcb7/FODGE-${REALVERSION}.tar.gz"
SOURCEFILE="FODGE-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/setuptools[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
