# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Document Text Recognition (docTR): deep Learning for high-performance OCR on documents."

HOMEPAGE=""
LICENSE="Apache License"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME//-/_}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME//-/_}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="contrib dev docs html quality testing viz"
DEPENDENCIES="dev-python/torch[${PYTHON_USEDEP}]
	dev-python/torchvision[${PYTHON_USEDEP}]
	dev-python/onnx[${PYTHON_USEDEP}]
	<dev-python/numpy-3.0.0[${PYTHON_USEDEP}]
	<dev-python/scipy-2.0.0[${PYTHON_USEDEP}]
	<dev-python/h5py-4.0.0[${PYTHON_USEDEP}]
	dev-python/opencv-python[${PYTHON_USEDEP}]
	dev-python/pypdfium2[${PYTHON_USEDEP}]
	<dev-python/pyclipper-2.0.0[${PYTHON_USEDEP}]
	<dev-python/shapely-3.0.0[${PYTHON_USEDEP}]
	dev-python/langdetect[${PYTHON_USEDEP}]
	<dev-python/rapidfuzz-4.0.0[${PYTHON_USEDEP}]
	dev-python/huggingface-hub[${PYTHON_USEDEP}]
	>=dev-python/pillow-9.2.0[${PYTHON_USEDEP}]
	>=dev-python/defusedxml-0.7.0[${PYTHON_USEDEP}]
	>=dev-python/anyascii-0.3.2[${PYTHON_USEDEP}]
	>=dev-python/validators-0.18.0[${PYTHON_USEDEP}]
	>=dev-python/tqdm-4.30.0[${PYTHON_USEDEP}]
	html? ( >=dev-python/weasyprint-55.0[${PYTHON_USEDEP}] )
	viz? ( >=dev-python/matplotlib-3.1.0[${PYTHON_USEDEP}] )
	viz? ( dev-python/mplcursors[${PYTHON_USEDEP}] )
	contrib? ( dev-python/onnxruntime[${PYTHON_USEDEP}] )
	testing? ( >=dev-python/pytest-5.3.2[${PYTHON_USEDEP}] )
	testing? ( >=dev-python/coverage-4.5.4[${PYTHON_USEDEP}] )
	testing? ( dev-python/onnxruntime[${PYTHON_USEDEP}] )
	testing? ( >=dev-python/requests-2.20.0[${PYTHON_USEDEP}] )
	testing? ( >=dev-python/psutil-5.9.5[${PYTHON_USEDEP}] )
	quality? ( dev-python/ruff[${PYTHON_USEDEP}] )
	quality? ( >=dev-python/mypy-0.812[${PYTHON_USEDEP}] )
	quality? ( dev-python/pre-commit[${PYTHON_USEDEP}] )
	docs? ( >=dev-python/sphinx-3.0.0[${PYTHON_USEDEP}] )
	docs? ( >=dev-python/sphinxemoji-0.1.8[${PYTHON_USEDEP}] )
	docs? ( >=dev-python/sphinx-copybutton-0.3.1[${PYTHON_USEDEP}] )
	docs? ( <dev-python/docutils-0.22[${PYTHON_USEDEP}] )
	docs? ( >=dev-python/recommonmark-0.7.1[${PYTHON_USEDEP}] )
	docs? ( dev-python/sphinx-markdown-tables[${PYTHON_USEDEP}] )
	docs? ( >=dev-python/sphinx-tabs-3.3.0[${PYTHON_USEDEP}] )
	docs? ( >=dev-python/furo-2022.3.4[${PYTHON_USEDEP}] )
	dev? ( dev-python/torch[${PYTHON_USEDEP}] )
	dev? ( dev-python/torchvision[${PYTHON_USEDEP}] )
	dev? ( dev-python/onnx[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/weasyprint-55.0[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/matplotlib-3.1.0[${PYTHON_USEDEP}] )
	dev? ( dev-python/mplcursors[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/pytest-5.3.2[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/coverage-4.5.4[${PYTHON_USEDEP}] )
	dev? ( dev-python/onnxruntime[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/requests-2.20.0[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/psutil-5.9.5[${PYTHON_USEDEP}] )
	dev? ( dev-python/ruff[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/mypy-1.0[${PYTHON_USEDEP}] )
	dev? ( dev-python/pre-commit[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/sphinx-3.0.0[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/sphinxemoji-0.1.8[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/sphinx-copybutton-0.3.1[${PYTHON_USEDEP}] )
	dev? ( <dev-python/docutils-0.22[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/recommonmark-0.7.1[${PYTHON_USEDEP}] )
	dev? ( dev-python/sphinx-markdown-tables[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/sphinx-tabs-3.3.0[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/furo-2022.3.4[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
