# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Open Source Secure Provisioning SDK for NXP MCU/MPU"

HOMEPAGE=""
LICENSE="BSD"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="all can dk6 examples jlink lauterbach oscca pemicro pqc"
DEPENDENCIES="<dev-python/asn1crypto-2.0[${PYTHON_USEDEP}]
	<dev-python/bincopy-21.0[${PYTHON_USEDEP}]
	<dev-python/bitstring-5.0[${PYTHON_USEDEP}]
	dev-python/click-command-tree[${PYTHON_USEDEP}]
	<dev-python/click-option-group-1.0[${PYTHON_USEDEP}]
	<dev-python/click-9.0[${PYTHON_USEDEP}]
	<dev-python/colorama-1.0[${PYTHON_USEDEP}]
	<dev-python/crcmod-2.0[${PYTHON_USEDEP}]
	<dev-python/cryptography-46.0[${PYTHON_USEDEP}]
	<dev-python/deepmerge-3.0[${PYTHON_USEDEP}]
	<dev-python/fastjsonschema-3.0[${PYTHON_USEDEP}]
	<dev-python/filelock-4.0[${PYTHON_USEDEP}]
	dev-python/hexdump[${PYTHON_USEDEP}]
	<dev-python/importlib-metadata-7.0[${PYTHON_USEDEP}]
	dev-python/libusbsio[${PYTHON_USEDEP}]
	dev-python/libuuu[${PYTHON_USEDEP}]
	dev-python/oscrypto[${PYTHON_USEDEP}]
	<dev-python/packaging-26.0[${PYTHON_USEDEP}]
	<dev-python/platformdirs-5.0[${PYTHON_USEDEP}]
	<dev-python/prettytable-4.0[${PYTHON_USEDEP}]
	<dev-python/pyasn1-1.0[${PYTHON_USEDEP}]
	<dev-python/pyserial-4.0[${PYTHON_USEDEP}]
	<dev-python/requests-3.0[${PYTHON_USEDEP}]
	<dev-python/ruamel-yaml-1.0[${PYTHON_USEDEP}]
	<dev-python/setuptools-scm-9.0[${PYTHON_USEDEP}]
	<dev-python/setuptools-81.0[${PYTHON_USEDEP}]
	dev-python/sly[${PYTHON_USEDEP}]
	dev-python/spsdk-mcu-link[${PYTHON_USEDEP}]
	dev-python/spsdk-pyocd[${PYTHON_USEDEP}]
	<dev-python/typing-extensions-5.0[${PYTHON_USEDEP}]
	dev-python/x690[${PYTHON_USEDEP}]
	all? ( dev-python/spsdk[${PYTHON_USEDEP}] )
	all? ( dev-python/spsdk[${PYTHON_USEDEP}] )
	all? ( dev-python/spsdk[${PYTHON_USEDEP}] )
	all? ( dev-python/spsdk[${PYTHON_USEDEP}] )
	all? ( dev-python/spsdk[${PYTHON_USEDEP}] )
	all? ( dev-python/spsdk[${PYTHON_USEDEP}] )
	all? ( dev-python/spsdk[${PYTHON_USEDEP}] )
	all? ( dev-python/spsdk[${PYTHON_USEDEP}] )
	can? ( dev-python/python-can[${PYTHON_USEDEP}] )
	dk6? ( dev-python/pyftdi[${PYTHON_USEDEP}] )
	dk6? ( dev-python/pylibftdi[${PYTHON_USEDEP}] )
	dk6? ( dev-python/ftd2xx[${PYTHON_USEDEP}] )
	examples? ( dev-python/flask[${PYTHON_USEDEP}] )
	examples? ( dev-python/requests[${PYTHON_USEDEP}] )
	examples? ( dev-python/ipython[${PYTHON_USEDEP}] )
	examples? ( dev-python/notebook[${PYTHON_USEDEP}] )
	examples? ( dev-python/ipywidgets[${PYTHON_USEDEP}] )
	jlink? ( dev-python/spsdk-jlink[${PYTHON_USEDEP}] )
	lauterbach? ( dev-python/spsdk-lauterbach[${PYTHON_USEDEP}] )
	oscca? ( dev-python/gmssl[${PYTHON_USEDEP}] )
	pemicro? ( dev-python/spsdk-pemicro[${PYTHON_USEDEP}] )
	pqc? ( dev-python/spsdk-pqc[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
