# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Python downloader for saving m3u8 video to local MP4 file."

HOMEPAGE="https://github.com/songs18/m3u8_To_MP4"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/2b/30/58eb9b8af0c3f5e6f7d42c45af28de3e61c8e31fceed60458dd466ea54cd/m3u8-To-MP4-${REALVERSION}.tar.gz"
SOURCEFILE="m3u8-To-MP4-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/iso8601[${PYTHON_USEDEP}]
	dev-python/m3u8[${PYTHON_USEDEP}]
	dev-python/pycryptodome[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
