# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="BS-RoFormer - Band-Split Rotary Transformer for SOTA Music Source Separation"

HOMEPAGE="https://github.com/lucidrains/BS-RoFormer"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/18/d6/b0c48530d09eb4fa94ebc9283728212d42b277234e8512ee73b7592656f3/bs_roformer-${REALVERSION}.tar.gz"
SOURCEFILE="bs_roformer-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/beartype[${PYTHON_USEDEP}]
	dev-python/einops[${PYTHON_USEDEP}]
	dev-python/librosa[${PYTHON_USEDEP}]
	dev-python/rotary-embedding-torch[${PYTHON_USEDEP}]
	dev-python/torch[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
