# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="More Collections! Some useful data structures for dealing with Data"

HOMEPAGE="https://github.com/klahnakoski/mo-collections"
LICENSE="MPL 2.0"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME//-/_}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME//-/_}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="tests"
DEPENDENCIES="dev-python/mo-dots[${PYTHON_USEDEP}]
	dev-python/mo-future[${PYTHON_USEDEP}]
	dev-python/mo-kwargs[${PYTHON_USEDEP}]
	dev-python/mo-logs[${PYTHON_USEDEP}]
	tests? ( dev-python/mo-testing[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
