# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Python utilities by the Professorship of Environmental Sensing and Modeling at the Technical University of Munich"

HOMEPAGE="https://github.com/tum-esm/utils"
LICENSE="AGPL-3"
SRC_URI="https://files.pythonhosted.org/packages/21/9f/55eb4fb495114b845da21f93bd0770bfee1dfd876ee5e578af16c4cf3a5a/tum_esm_utils-${REALVERSION}.tar.gz"
SOURCEFILE="tum_esm_utils-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/filelock[${PYTHON_USEDEP}]
	dev-python/requests[${PYTHON_USEDEP}]
	dev-python/psutil[${PYTHON_USEDEP}]
	dev-python/pendulum[${PYTHON_USEDEP}]
	dev-python/polars[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
