# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="graphene-file-upload"
REALVERSION="1.3.0"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
REPO_URI="http://pypi.python.org/packages/source/${REALNAME:0:1}/${REALNAME}/"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
DISTUTILS_USE_PEP517=standalone

inherit gs-pypi

DESCRIPTION="Lib for adding file upload functionality to GraphQL mutations in Graphene Django and Flask-Graphql"

HOMEPAGE="https://github.com/lmcgartland/graphene-file-upload"
LICENSE=""
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="all django flask tests"
DEPENDENCIES="dev-python/six[${PYTHON_USEDEP}]
	all? ( dev-python/Flask[${PYTHON_USEDEP}] )
	all? ( dev-python/graphene[${PYTHON_USEDEP}] )
	all? ( dev-python/Flask-Graphql[${PYTHON_USEDEP}] )
	all? ( dev-python/graphene-django[${PYTHON_USEDEP}] )
	django? ( dev-python/graphene-django[${PYTHON_USEDEP}] )
	flask? ( dev-python/Flask[${PYTHON_USEDEP}] )
	flask? ( dev-python/graphene[${PYTHON_USEDEP}] )
	flask? ( dev-python/Flask-Graphql[${PYTHON_USEDEP}] )
	tests? ( dev-python/coverage[${PYTHON_USEDEP}] )
	tests? ( dev-python/pytest[${PYTHON_USEDEP}] )
	tests? ( dev-python/pytest-cov[${PYTHON_USEDEP}] )
	tests? ( dev-python/pytest-django[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
