# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="ansimarkup"
REALVERSION="1.5.0"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
REPO_URI="http://pypi.python.org/packages/source/${REALNAME:0:1}/${REALNAME}/"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
DISTUTILS_USE_PEP517=standalone

inherit gs-pypi

DESCRIPTION="Produce colored terminal text with an xml-like markup"

HOMEPAGE="https://github.com/gvalkov/python-ansimarkup"
LICENSE="Revised BSD License"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="devel tests"
DEPENDENCIES="dev-python/colorama[${PYTHON_USEDEP}]
	devel? ( dev-python/bumpversion[${PYTHON_USEDEP}] )
	devel? ( dev-python/check-manifest[${PYTHON_USEDEP}] )
	devel? ( dev-python/readme-renderer[${PYTHON_USEDEP}] )
	devel? ( dev-python/flake8[${PYTHON_USEDEP}] )
	devel? ( dev-python/pep8-naming[${PYTHON_USEDEP}] )
	tests? ( dev-python/tox[${PYTHON_USEDEP}] )
	tests? ( dev-python/pytest[${PYTHON_USEDEP}] )
	tests? ( dev-python/pytest-cov[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
