# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Polemarch is ansible based service for orchestration infrastructure."

HOMEPAGE="https://gitlab.com/vstconsulting/polemarch"
LICENSE="AGPL-3+"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="mysql postgresql test"
DEPENDENCIES="dev-python/vstutils[${PYTHON_USEDEP}]
	~dev-python/markdown2-2.4.9[${PYTHON_USEDEP}]
	dev-python/GitPython[${PYTHON_USEDEP}]
	dev-python/gitdb2[${PYTHON_USEDEP}]
	~dev-python/requests-2.31.0[${PYTHON_USEDEP}]
	~dev-python/urllib3-1.26.16[${PYTHON_USEDEP}]
	dev-python/polemarch-ansible[${PYTHON_USEDEP}]
	dev-python/netaddr[${PYTHON_USEDEP}]
	dev-python/coreapi[${PYTHON_USEDEP}]
	dev-python/coreschema[${PYTHON_USEDEP}]
	mysql? ( <dev-python/mysqlclient-2.2[${PYTHON_USEDEP}] )
	postgresql? ( dev-python/psycopg[${PYTHON_USEDEP}] )
	test? ( dev-python/django-test-migrations[${PYTHON_USEDEP}] )
	test? ( dev-python/vstutils[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
