# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="This package is used for building automation functions for rpa within Bosch"

HOMEPAGE="https://github.boschdevcloud.com/LZV2SZH/BoschRpaMagicBox"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/42/37/fe6311fe321360032bb13b5950cf89cfbe4684f47d03002f1dcf3981ad96/boschrpamagicbox-${REALVERSION}.tar.gz"
SOURCEFILE="boschrpamagicbox-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/pyperclip[${PYTHON_USEDEP}]
	dev-python/pysmb[${PYTHON_USEDEP}]
	~dev-python/selenium-4.8.0[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
