# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="PySAD is an open-source python framework for anomaly detection on streaming multivariate data."

HOMEPAGE="https://github.com/selimfirat/pysad"
LICENSE="BSD 3-Clause License"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="inqmad pandas rrcf slop xstream"
DEPENDENCIES="dev-python/numpy[${PYTHON_USEDEP}]
	dev-python/scikit-learn[${PYTHON_USEDEP}]
	dev-python/scipy[${PYTHON_USEDEP}]
	dev-python/pyod[${PYTHON_USEDEP}]
	dev-python/combo[${PYTHON_USEDEP}]
	rrcf? ( dev-python/rrcf[${PYTHON_USEDEP}] )
	slop? ( dev-python/PyNomaly[${PYTHON_USEDEP}] )
	xstream? ( dev-python/mmh3[${PYTHON_USEDEP}] )
	pandas? ( dev-python/pandas[${PYTHON_USEDEP}] )
	inqmad? ( dev-python/jax[${PYTHON_USEDEP}] )
	inqmad? ( dev-python/jaxlib[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
