# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Python conversion of Timbre Toolbox"

HOMEPAGE="https://gitlab.com/python-audio-feature-extraction/pytimbre"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/e3/a5/ef9b57ddf2af55b4d74b5309ebe0414cf9be4a24a312780df545022446dd/pytimbre-${REALVERSION}.tar.gz"
SOURCEFILE="pytimbre-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/colorednoise[${PYTHON_USEDEP}]
	>=dev-python/numpy-1.21.5[${PYTHON_USEDEP}]
	>=dev-python/pandas-1.4.3[${PYTHON_USEDEP}]
	dev-python/python_speech_features[${PYTHON_USEDEP}]
	>=dev-python/scipy-1.9.1[${PYTHON_USEDEP}]
	>=dev-python/statsmodels-0.13.2[${PYTHON_USEDEP}]
	>=dev-python/json5-0.9.0[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
