# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Package containing tooling for developing nominode engines"

HOMEPAGE="https://gitlab.com/nomnomdata/tools/nomnomdata-engine"
LICENSE="LGPL-3.0-only"
SRC_URI="https://files.pythonhosted.org/packages/64/73/fa9c8ff36da81852496dd8645bd29e9c6b4951920a8d1936fccd5838a6d3/nomnomdata_engine-${REALVERSION}.tar.gz"
SOURCEFILE="nomnomdata_engine-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/dunamai[${PYTHON_USEDEP}]
	dev-python/httmock[${PYTHON_USEDEP}]
	dev-python/nomnomdata-cli[${PYTHON_USEDEP}]
	dev-python/pyyaml[${PYTHON_USEDEP}]
	dev-python/requests[${PYTHON_USEDEP}]
	dev-python/wrapt[${PYTHON_USEDEP}]
	dev-python/MarkupSafe[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
