# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="a more pythonic way to access the windows registry as winreg"

HOMEPAGE="https://github.com/bitranox/lib_registry"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/0f/42/9bdc28b31866b7d157d3bfec911cf7675ad104a073d0a05b0f1b8a9ba833/lib_registry-${REALVERSION}.tar.gz"
SOURCEFILE="lib_registry-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/click[${PYTHON_USEDEP}]
	dev-python/cli-exit-tools[${PYTHON_USEDEP}]
	dev-python/fake-winreg[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
