# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="A package to create representative microdata for the US."

HOMEPAGE=""
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME//-/_}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME//-/_}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="dev"
DEPENDENCIES="dev-python/policyengine-us[${PYTHON_USEDEP}]
	dev-python/policyengine-core[${PYTHON_USEDEP}]
	>=dev-python/pandas-2.3.1[${PYTHON_USEDEP}]
	>=dev-python/requests-2.25.0[${PYTHON_USEDEP}]
	>=dev-python/tqdm-4.60.0[${PYTHON_USEDEP}]
	dev-python/microdf-python[${PYTHON_USEDEP}]
	>=dev-python/setuptools-60.0[${PYTHON_USEDEP}]
	dev-python/microimpute[${PYTHON_USEDEP}]
	dev-python/pip-system-certs[${PYTHON_USEDEP}]
	dev-python/google-cloud-storage[${PYTHON_USEDEP}]
	>=dev-python/google-auth-2.0.0[${PYTHON_USEDEP}]
	>=dev-python/scipy-1.15.3[${PYTHON_USEDEP}]
	>=dev-python/statsmodels-0.14.5[${PYTHON_USEDEP}]
	>=dev-python/openpyxl-3.1.5[${PYTHON_USEDEP}]
	>=dev-python/tables-3.10.2[${PYTHON_USEDEP}]
	dev-python/torch[${PYTHON_USEDEP}]
	dev-python/us[${PYTHON_USEDEP}]
	>=dev-python/sqlalchemy-2.0.41[${PYTHON_USEDEP}]
	dev-python/sqlmodel[${PYTHON_USEDEP}]
	>=dev-python/xlrd-2.0.2[${PYTHON_USEDEP}]
	dev? ( dev-python/black[${PYTHON_USEDEP}] )
	dev? ( dev-python/pytest[${PYTHON_USEDEP}] )
	dev? ( dev-python/quantile-forest[${PYTHON_USEDEP}] )
	dev? ( dev-python/tabulate[${PYTHON_USEDEP}] )
	dev? ( dev-python/furo[${PYTHON_USEDEP}] )
	dev? ( dev-python/jupyter-book[${PYTHON_USEDEP}] )
	dev? ( dev-python/mystmd[${PYTHON_USEDEP}] )
	dev? ( dev-python/yaml-changelog[${PYTHON_USEDEP}] )
	dev? ( dev-python/build[${PYTHON_USEDEP}] )
	dev? ( dev-python/tomli[${PYTHON_USEDEP}] )
	dev? ( dev-python/itables[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
