# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="KUKA-youbot"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="package for easy KUKA-youbot control"

HOMEPAGE="https://github.com/MarkT5/YouBotKUKA"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/0b/06/53c4a7b61ec656f00753dabcf22cd9e50fe6141b13190c34b3c94842a1b9/${LITERALNAME//-/_}-${REALVERSION}.tar.gz"
SOURCEFILE="${LITERALNAME//-/_}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=">=dev-python/setuptools-40.9.0[${PYTHON_USEDEP}]
	>=dev-python/numpy-1.23.0[${PYTHON_USEDEP}]
	dev-python/opencv-python[${PYTHON_USEDEP}]
	dev-python/py-mjpeg[${PYTHON_USEDEP}]
	>=dev-python/paramiko-3.1.0[${PYTHON_USEDEP}]
	>=dev-python/pillow-9.4.0[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
