# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Easy Kit"

HOMEPAGE=""
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/30/d2/603957494ee202ebd6229b73a55ab6f5513c36e7a83da76c7f374a5afd69/ezkit-${REALVERSION}.tar.gz"
SOURCEFILE="ezkit-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=">=dev-python/loguru-0.7[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
