# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="A SQLite3 wrapper for python"

HOMEPAGE="https://github.com/IvanVZabrodin/QueriPlug"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/b6/04/0346145b3489d67bebfa278c7456864e3484ef4fa55b65343b0b355ba0b8/QueriPlug-${REALVERSION}.tar.gz"
SOURCEFILE="QueriPlug-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=""
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
