# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Solana Python API"

HOMEPAGE="https://github.com/michaelhly/solanapy"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/construct-typing[${PYTHON_USEDEP}]
	<dev-python/httpx-0.24.0[${PYTHON_USEDEP}]
	<dev-python/requests-3.0[${PYTHON_USEDEP}]
	>=dev-python/typing-extensions-3.10.0[${PYTHON_USEDEP}]
	<dev-python/cachetools-5.0.0[${PYTHON_USEDEP}]
	dev-python/types-cachetools[${PYTHON_USEDEP}]
	dev-python/jsonrpcclient[${PYTHON_USEDEP}]
	<dev-python/websockets-11.0[${PYTHON_USEDEP}]
	dev-python/jsonrpcserver[${PYTHON_USEDEP}]
	dev-python/apischema[${PYTHON_USEDEP}]
	dev-python/based58[${PYTHON_USEDEP}]
	dev-python/solders[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
