# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Nautobot tools project by Data Ductus"

HOMEPAGE=""
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/66/06/2a07644b3732f48af29b0a95fc0f28897e7166d879346b11d14443e53ebe/nautobot_tools_dd-${REALVERSION}.tar.gz"
SOURCEFILE="nautobot_tools_dd-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/nautobot[${PYTHON_USEDEP}]
	dev-python/yangson[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
