# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="aws-encryption-sdk-cli"
REALVERSION="4.1.0"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
REPO_URI="http://pypi.python.org/packages/source/${REALNAME:0:1}/${REALNAME}/"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
DISTUTILS_USE_PEP517=standalone

inherit gs-pypi

DESCRIPTION="This command line tool can be used to encrypt and decrypt files and directories using the AWS Encryption SDK."

HOMEPAGE="http://aws-encryption-sdk-cli.readthedocs.io/en/latest/"
LICENSE="Apache License 2.0"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/base64io[${PYTHON_USEDEP}]
	dev-python/aws-encryption-sdk[${PYTHON_USEDEP}]
	dev-python/setuptools[${PYTHON_USEDEP}]
	dev-python/attrs[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
