# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Python tools for quick access to DataBC geo-data available via WFS"

HOMEPAGE="https://github.com/smnorris/bcdata"
LICENSE="Apache-2.0"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="test"
DEPENDENCIES="dev-python/geoalchemy2[${PYTHON_USEDEP}]
	dev-python/geopandas[${PYTHON_USEDEP}]
	~dev-python/owslib-0.29[${PYTHON_USEDEP}]
	dev-python/psycopg2-binary[${PYTHON_USEDEP}]
	dev-python/rasterio[${PYTHON_USEDEP}]
	~dev-python/requests-2.31[${PYTHON_USEDEP}]
	~dev-python/sqlalchemy-2.0[${PYTHON_USEDEP}]
	dev-python/stamina[${PYTHON_USEDEP}]
	test? ( >=dev-python/pytest-3.0[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
