# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Utilities for Jupyter Physical Science Lab project"

HOMEPAGE="https://github.com/JupyterPhysSciLab/JPSLUtils"
LICENSE="GPL-3+"
SRC_URI="https://files.pythonhosted.org/packages/6b/8b/d30afb8bfd0da859af08c9f682d459ad3bef325ce0c459af54054fe1cbcc/JPSLUtils-${REALVERSION}.tar.gz"
SOURCEFILE="JPSLUtils-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/jupyter[${PYTHON_USEDEP}]
	dev-python/JPSLMenus[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
