# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="AKEYLESS Cloud ID Retriever"

HOMEPAGE="https://www.akeyless.io/"
LICENSE="Apache-2.0"
SRC_URI="https://files.pythonhosted.org/packages/63/74/00d63bb074e6a0b93c65bc0b13fed95c636128fd1b45aa666e8b0b0df655/akeyless_cloud_id-${REALVERSION}.tar.gz"
SOURCEFILE="akeyless_cloud_id-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/boto3[${PYTHON_USEDEP}]
	dev-python/google[${PYTHON_USEDEP}]
	dev-python/google-api-python-client[${PYTHON_USEDEP}]
	dev-python/requests[${PYTHON_USEDEP}]
	dev-python/urllib3[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
