# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Metadata tracking tools help to manage an increasingly diverse set of life science, environmental and biomedical experiments"

HOMEPAGE=""
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="notebook"
DEPENDENCIES="<dev-python/setuptools-81.0[${PYTHON_USEDEP}]
	~dev-python/numpy-2.2.4[${PYTHON_USEDEP}]
	~dev-python/networkx-3.4.2[${PYTHON_USEDEP}]
	<dev-python/jsonschema-5.0[${PYTHON_USEDEP}]
	<dev-python/pandas-3.0[${PYTHON_USEDEP}]
	>=dev-python/openpyxl-3.1.5[${PYTHON_USEDEP}]
	~dev-python/lxml-6.0.2[${PYTHON_USEDEP}]
	~dev-python/requests-2.32.4[${PYTHON_USEDEP}]
	~dev-python/iso8601-2.1.0[${PYTHON_USEDEP}]
	~dev-python/chardet-5.2.0[${PYTHON_USEDEP}]
	~dev-python/jinja2-3.1.4[${PYTHON_USEDEP}]
	~dev-python/beautifulsoup4-4.14.2[${PYTHON_USEDEP}]
	dev-python/mzml2isa[${PYTHON_USEDEP}]
	dev-python/biopython[${PYTHON_USEDEP}]
	~dev-python/progressbar2-4.5.0[${PYTHON_USEDEP}]
	~dev-python/pyyaml-6.0.2[${PYTHON_USEDEP}]
	~dev-python/rdflib-7.2.1[${PYTHON_USEDEP}]
	~dev-python/python-dateutil-2.9.0_p0[${PYTHON_USEDEP}]
	>=dev-python/flask-3.1.1[${PYTHON_USEDEP}]
	>=dev-python/flask-sqlalchemy-3.0.2[${PYTHON_USEDEP}]
	~dev-python/sqlalchemy-2.0.31[${PYTHON_USEDEP}]
	dev-python/graphene[${PYTHON_USEDEP}]
	dev-python/graphql-core[${PYTHON_USEDEP}]
	dev-python/ruff[${PYTHON_USEDEP}]
	>=dev-python/pytest-timeout-2.4.0[${PYTHON_USEDEP}]
	notebook? ( dev-python/bokeh[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
