# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=wheel

inherit python-r1 gs-pypi

DESCRIPTION="Tools for estimating and computing Constant Frisch Elasticity (CFE) demands. [wheel]"

HOMEPAGE="https://github.com/ligon/CFEDemands"
LICENSE="Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International license"
SRC_URI="https://files.pythonhosted.org/packages/e9/ea/e79f49b046e7ae348e95ea3f191183d179e12502f51ce49b1545fb26be59/cfedemands-${REALVERSION}-py2.py3-none-any.whl"
SOURCEFILE="cfedemands-${REALVERSION}-py2.py3-none-any.whl"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/consumerdemands[${PYTHON_USEDEP}]
	>=dev-python/matplotlib-3.5.1[${PYTHON_USEDEP}]
	>=dev-python/numpy-1.21.5[${PYTHON_USEDEP}]
	>=dev-python/pandas-1.3.5[${PYTHON_USEDEP}]
	>=dev-python/scipy-1.7.3[${PYTHON_USEDEP}]
	>=dev-python/importlib-metadata-6.7.0[${PYTHON_USEDEP}]
	dev-python/fsspec[${PYTHON_USEDEP}]
	virtual/allow-pypi-wheels"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
