# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="SDK for FlightRadar24"

HOMEPAGE="https://github.com/JeanExtreme002/FlightRadarAPI"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/6b/0f/ca8156c6adc812e0809377a52bb494ad928ebc60f2b5624e7ddfd5981a1a/flightradarapi-${REALVERSION}.tar.gz"
SOURCEFILE="flightradarapi-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="tests"
DEPENDENCIES="dev-python/Brotli[${PYTHON_USEDEP}]
	dev-python/requests[${PYTHON_USEDEP}]
	tests? ( dev-python/pytest[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
