# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="A lightweight web API framework based on Flask and marshmallow-code projects."

HOMEPAGE=""
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/b0/fd/80e8bf25fd8ecf7b6b82eb09ec3e97a8a3cd68bbde639db0f8c40604e0bb/apiflask-${REALVERSION}.tar.gz"
SOURCEFILE="apiflask-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="async dotenv yaml"
DEPENDENCIES=">=dev-python/flask-2.0[${PYTHON_USEDEP}]
	dev-python/flask-marshmallow[${PYTHON_USEDEP}]
	>=dev-python/marshmallow-3.20[${PYTHON_USEDEP}]
	dev-python/webargs[${PYTHON_USEDEP}]
	dev-python/Flask-HTTPAuth[${PYTHON_USEDEP}]
	>=dev-python/apispec-6.0[${PYTHON_USEDEP}]
	async? ( >=dev-python/asgiref-3.2[${PYTHON_USEDEP}] )
	dotenv? ( dev-python/python-dotenv[${PYTHON_USEDEP}] )
	yaml? ( dev-python/pyyaml[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
