# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Python wrapper for the steam materials package."

HOMEPAGE="https://gitlab.cern.ch/steam/steam-material-library"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/3f/aa/dfd3bab8f5e33a7a686c0449a2b184c20d10e3237d77c9dc615ee1dde783/steam_materials-${REALVERSION}.tar.gz"
SOURCEFILE="steam_materials-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/numpy[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
