# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Investment analytics and machine learning tools"

HOMEPAGE="https://s3pip-library.s3.amazonaws.com"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/eb/40/cb5ad3bc38444799114b15f114e6053c4d54fbcafc6687e5b5d530ba5087/pycondorraven-${REALVERSION}.tar.gz"
SOURCEFILE="pycondorraven-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=""
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
