# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Access, Deisotope, and Charge Deconvolute Mass Spectra"

HOMEPAGE=""
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME//-/_}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME//-/_}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="all cli com mzmlb net plot"
DEPENDENCIES=">=dev-python/numpy-2.0.0[${PYTHON_USEDEP}]
	dev-python/scipy[${PYTHON_USEDEP}]
	dev-python/six[${PYTHON_USEDEP}]
	dev-python/dill[${PYTHON_USEDEP}]
	dev-python/ms-peak-picker[${PYTHON_USEDEP}]
	dev-python/brain-isotopic-distribution[${PYTHON_USEDEP}]
	dev-python/pyteomics[${PYTHON_USEDEP}]
	dev-python/lxml[${PYTHON_USEDEP}]
	dev-python/psims[${PYTHON_USEDEP}]
	dev-python/python-idzip[${PYTHON_USEDEP}]
	dev-python/pyzstd[${PYTHON_USEDEP}]
	com? ( dev-python/comtypes[${PYTHON_USEDEP}] )
	net? ( dev-python/pythonnet[${PYTHON_USEDEP}] )
	plot? ( dev-python/matplotlib[${PYTHON_USEDEP}] )
	cli? ( dev-python/click[${PYTHON_USEDEP}] )
	mzmlb? ( dev-python/h5py[${PYTHON_USEDEP}] )
	mzmlb? ( dev-python/hdf5plugin[${PYTHON_USEDEP}] )
	all? ( dev-python/comtypes[${PYTHON_USEDEP}] )
	all? ( dev-python/pythonnet[${PYTHON_USEDEP}] )
	all? ( dev-python/matplotlib[${PYTHON_USEDEP}] )
	all? ( dev-python/click[${PYTHON_USEDEP}] )
	all? ( dev-python/h5py[${PYTHON_USEDEP}] )
	all? ( dev-python/hdf5plugin[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
