# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Colorist for Python"

HOMEPAGE="https://jakob-bagterp.github.io/colorist-for-python/"
LICENSE="3-Clause BSD License"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="testing"
DEPENDENCIES="testing? ( ~dev-python/coverage-7.8.2[${PYTHON_USEDEP}] )
	testing? ( ~dev-python/flake8-7.2.0[${PYTHON_USEDEP}] )
	testing? ( ~dev-python/mypy-1.16.0[${PYTHON_USEDEP}] )
	testing? ( ~dev-python/pytest-8.4.0[${PYTHON_USEDEP}] )
	testing? ( ~dev-python/pytest-cov-6.1.1[${PYTHON_USEDEP}] )
	testing? ( ~dev-python/tox-4.26.0[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
