# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Create sequential synthetic data of mixed types using a GAN."

HOMEPAGE="https://github.com/sdv-dev/DeepEcho"
LICENSE="BSL-1.1"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="dev test"
DEPENDENCIES="<dev-python/tqdm-5.0[${PYTHON_USEDEP}]
	<dev-python/numpy-2.0[${PYTHON_USEDEP}]
	>=dev-python/pandas-1.3.4[${PYTHON_USEDEP}]
	dev-python/torch[${PYTHON_USEDEP}]
	>=dev-python/pandas-1.5.0[${PYTHON_USEDEP}]
	dev-python/torch[${PYTHON_USEDEP}]
	dev? ( <dev-python/setuptools-49.2[${PYTHON_USEDEP}] )
	dev? ( dev-python/bumpversion[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/pip-9.0.1[${PYTHON_USEDEP}] )
	dev? ( <dev-python/watchdog-0.11[${PYTHON_USEDEP}] )
	dev? ( <dev-python/flake8-4.0[${PYTHON_USEDEP}] )
	dev? ( dev-python/flake8-absolute-import[${PYTHON_USEDEP}] )
	dev? ( dev-python/flake8-docstrings[${PYTHON_USEDEP}] )
	dev? ( dev-python/flake8-sfs[${PYTHON_USEDEP}] )
	dev? ( <dev-python/isort-5.0[${PYTHON_USEDEP}] )
	dev? ( <dev-python/pylint-3.0[${PYTHON_USEDEP}] )
	dev? ( dev-python/flake8-builtins[${PYTHON_USEDEP}] )
	dev? ( dev-python/flake8-debugger[${PYTHON_USEDEP}] )
	dev? ( dev-python/flake8-mock[${PYTHON_USEDEP}] )
	dev? ( dev-python/dlint[${PYTHON_USEDEP}] )
	dev? ( dev-python/flake8-eradicate[${PYTHON_USEDEP}] )
	dev? ( dev-python/flake8-mutable[${PYTHON_USEDEP}] )
	dev? ( dev-python/flake8-fixme[${PYTHON_USEDEP}] )
	dev? ( dev-python/flake8-multiline-containers[${PYTHON_USEDEP}] )
	dev? ( dev-python/flake8-quotes[${PYTHON_USEDEP}] )
	dev? ( dev-python/flake8-variables-names[${PYTHON_USEDEP}] )
	dev? ( dev-python/pep8-naming[${PYTHON_USEDEP}] )
	dev? ( dev-python/flake8-expression-complexity[${PYTHON_USEDEP}] )
	dev? ( dev-python/flake8-print[${PYTHON_USEDEP}] )
	dev? ( dev-python/autoflake[${PYTHON_USEDEP}] )
	dev? ( <dev-python/autopep8-1.6[${PYTHON_USEDEP}] )
	dev? ( <dev-python/twine-4.0[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/wheel-0.30.0[${PYTHON_USEDEP}] )
	dev? ( <dev-python/coverage-6.0[${PYTHON_USEDEP}] )
	dev? ( <dev-python/tox-4.0[${PYTHON_USEDEP}] )
	dev? ( dev-python/invoke[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/pytest-3.4.2[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/pytest-cov-2.6.0[${PYTHON_USEDEP}] )
	dev? ( <dev-python/pytest-rerunfailures-10.0[${PYTHON_USEDEP}] )
	dev? ( <dev-python/jupyter-2.0[${PYTHON_USEDEP}] )
	dev? ( dev-python/rundoc[${PYTHON_USEDEP}] )
	test? ( >=dev-python/pytest-3.4.2[${PYTHON_USEDEP}] )
	test? ( >=dev-python/pytest-cov-2.6.0[${PYTHON_USEDEP}] )
	test? ( <dev-python/pytest-rerunfailures-10.0[${PYTHON_USEDEP}] )
	test? ( <dev-python/jupyter-2.0[${PYTHON_USEDEP}] )
	test? ( dev-python/rundoc[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
