# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="0.0.125.dev0"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION=""

HOMEPAGE=""
LICENSE="AGPL-3"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME//-/_}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME//-/_}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="all browser-use notifications security"
DEPENDENCIES="<dev-python/typing-extensions-5.0.0[${PYTHON_USEDEP}]
	<dev-python/click-8.2.0[${PYTHON_USEDEP}]
	dev-python/openai[${PYTHON_USEDEP}]
	dev-python/tree-sitter-languages[${PYTHON_USEDEP}]
	dev-python/python-gitlab[${PYTHON_USEDEP}]
	<dev-python/pygithub-2.2.0[${PYTHON_USEDEP}]
	dev-python/azure-devops[${PYTHON_USEDEP}]
	<dev-python/gitpython-3.2.0[${PYTHON_USEDEP}]
	<dev-python/pydantic-2.11.0[${PYTHON_USEDEP}]
	dev-python/pydantic-ai[${PYTHON_USEDEP}]
	dev-python/google-cloud-aiplatform[${PYTHON_USEDEP}]
	dev-python/google-genai[${PYTHON_USEDEP}]
	<dev-python/libcst-1.2.0[${PYTHON_USEDEP}]
	<dev-python/sqlalchemy-2.1.0[${PYTHON_USEDEP}]
	dev-python/patched-code2prompt[${PYTHON_USEDEP}]
	<dev-python/pyyaml-7.0.0[${PYTHON_USEDEP}]
	dev-python/packageurl-python[${PYTHON_USEDEP}]
	<dev-python/semver-3.1.0[${PYTHON_USEDEP}]
	<dev-python/requests-2.33.0[${PYTHON_USEDEP}]
	<dev-python/chardet-5.3.0[${PYTHON_USEDEP}]
	<dev-python/attrs-23.3.0[${PYTHON_USEDEP}]
	dev-python/anthropic[${PYTHON_USEDEP}]
	<dev-python/rich-15.0.0[${PYTHON_USEDEP}]
	dev-python/chevron[${PYTHON_USEDEP}]
	dev-python/giturlparse[${PYTHON_USEDEP}]
	dev-python/eml-parser[${PYTHON_USEDEP}]
	<dev-python/csvkit-3.0.0[${PYTHON_USEDEP}]
	<dev-python/python-magic-0.5.0[${PYTHON_USEDEP}]
	<dev-python/scikit-learn-2.0.0[${PYTHON_USEDEP}]
	dev-python/json-repair[${PYTHON_USEDEP}]
	dev-python/dotenv[${PYTHON_USEDEP}]
	<dev-python/tree-sitter-0.22.0[${PYTHON_USEDEP}]
	~dev-python/numpy-1.26.4[${PYTHON_USEDEP}]
	~dev-python/pandas-2.2.3[${PYTHON_USEDEP}]
	~dev-python/scipy-1.13.1[${PYTHON_USEDEP}]
	<dev-python/boto3-2.0.0[${PYTHON_USEDEP}]
	<dev-python/urllib3-3.0.0[${PYTHON_USEDEP}]
	security? ( dev-python/semgrep[${PYTHON_USEDEP}] )
	all? ( dev-python/semgrep[${PYTHON_USEDEP}] )
	security? ( dev-python/owasp-depscan[${PYTHON_USEDEP}] )
	all? ( dev-python/owasp-depscan[${PYTHON_USEDEP}] )
	notifications? ( dev-python/slack-sdk[${PYTHON_USEDEP}] )
	all? ( dev-python/slack-sdk[${PYTHON_USEDEP}] )
	browser-use? ( dev-python/browser-use[${PYTHON_USEDEP}] )
	all? ( dev-python/browser-use[${PYTHON_USEDEP}] )
	browser-use? ( dev-python/playwright[${PYTHON_USEDEP}] )
	all? ( dev-python/playwright[${PYTHON_USEDEP}] )
	browser-use? ( dev-python/langchain-google-genai[${PYTHON_USEDEP}] )
	all? ( dev-python/langchain-google-genai[${PYTHON_USEDEP}] )
	browser-use? ( dev-python/langchain-openai[${PYTHON_USEDEP}] )
	all? ( dev-python/langchain-openai[${PYTHON_USEDEP}] )
	browser-use? ( dev-python/langchain-anthropic[${PYTHON_USEDEP}] )
	all? ( dev-python/langchain-anthropic[${PYTHON_USEDEP}] )
	browser-use? ( <dev-python/pillow-10.5.0[${PYTHON_USEDEP}] )
	all? ( <dev-python/pillow-10.5.0[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
