# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION=""

HOMEPAGE="https://github.com/aivclab/jord"
LICENSE="Apache-2.0"
SRC_URI="https://files.pythonhosted.org/packages/00/64/eb8281edeec41696210bc4478eb756f30e7645a439351a710b6ffea65a4e/jord-${REALVERSION}.tar.gz"
SOURCEFILE="jord-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="all dev docs fiona geopandas legacy network pil q qgis shapely tests"
DEPENDENCIES="dev-python/Apppath[${PYTHON_USEDEP}]
	dev-python/Draugr[${PYTHON_USEDEP}]
	>=dev-python/numpy-1.20.0[${PYTHON_USEDEP}]
	>=dev-python/pyzmq-1.1.1[${PYTHON_USEDEP}]
	dev-python/sorcery[${PYTHON_USEDEP}]
	>=dev-python/sympy-1.1.1[${PYTHON_USEDEP}]
	>=dev-python/tqdm-1.1.1[${PYTHON_USEDEP}]
	dev-python/Warg[${PYTHON_USEDEP}]
	all? ( >=dev-python/pytest-4.3.0[${PYTHON_USEDEP}] )
	all? ( dev-python/Warg[${PYTHON_USEDEP}] )
	all? ( >=dev-python/pyzmq-1.1.1[${PYTHON_USEDEP}] )
	all? ( dev-python/pre-commit[${PYTHON_USEDEP}] )
	all? ( >=dev-python/sphinx-4.0.1[${PYTHON_USEDEP}] )
	all? ( dev-python/pyproj[${PYTHON_USEDEP}] )
	all? ( dev-python/shapely[${PYTHON_USEDEP}] )
	all? ( >=dev-python/tqdm-1.1.1[${PYTHON_USEDEP}] )
	all? ( dev-python/furo[${PYTHON_USEDEP}] )
	all? ( dev-python/Draugr[${PYTHON_USEDEP}] )
	all? ( dev-python/coveralls[${PYTHON_USEDEP}] )
	all? ( >=dev-python/twine-1.13.0[${PYTHON_USEDEP}] )
	all? ( >=dev-python/pip-22.1.2[${PYTHON_USEDEP}] )
	all? ( >=dev-python/sympy-1.1.1[${PYTHON_USEDEP}] )
	all? ( >=dev-python/wheel-0.33.0[${PYTHON_USEDEP}] )
	all? ( dev-python/fiona[${PYTHON_USEDEP}] )
	all? ( >=dev-python/pytest-4.4.1[${PYTHON_USEDEP}] )
	all? ( dev-python/sphinxcontrib-programoutput[${PYTHON_USEDEP}] )
	all? ( dev-python/pillow[${PYTHON_USEDEP}] )
	all? ( dev-python/networkx[${PYTHON_USEDEP}] )
	all? ( dev-python/importlib-metadata[${PYTHON_USEDEP}] )
	all? ( dev-python/mock[${PYTHON_USEDEP}] )
	all? ( >=dev-python/black-21.5_beta0[${PYTHON_USEDEP}] )
	all? ( dev-python/geopandas[${PYTHON_USEDEP}] )
	all? ( dev-python/importlib-resources[${PYTHON_USEDEP}] )
	all? ( >=dev-python/pytest-cov-2.11.1[${PYTHON_USEDEP}] )
	all? ( dev-python/sorcery[${PYTHON_USEDEP}] )
	all? ( dev-python/Apppath[${PYTHON_USEDEP}] )
	all? ( >=dev-python/numpy-1.20.0[${PYTHON_USEDEP}] )
	all? ( dev-python/pyside2[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/pytest-4.3.0[${PYTHON_USEDEP}] )
	dev? ( dev-python/Warg[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/pyzmq-1.1.1[${PYTHON_USEDEP}] )
	dev? ( dev-python/pre-commit[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/sphinx-4.0.1[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/tqdm-1.1.1[${PYTHON_USEDEP}] )
	dev? ( dev-python/furo[${PYTHON_USEDEP}] )
	dev? ( dev-python/Draugr[${PYTHON_USEDEP}] )
	dev? ( dev-python/coveralls[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/twine-1.13.0[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/pip-22.1.2[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/sympy-1.1.1[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/wheel-0.33.0[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/pytest-4.4.1[${PYTHON_USEDEP}] )
	dev? ( dev-python/sphinxcontrib-programoutput[${PYTHON_USEDEP}] )
	dev? ( dev-python/mock[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/black-21.5_beta0[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/pytest-cov-2.11.1[${PYTHON_USEDEP}] )
	dev? ( dev-python/sorcery[${PYTHON_USEDEP}] )
	dev? ( dev-python/Apppath[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/numpy-1.20.0[${PYTHON_USEDEP}] )
	docs? ( dev-python/furo[${PYTHON_USEDEP}] )
	docs? ( dev-python/sphinxcontrib-programoutput[${PYTHON_USEDEP}] )
	docs? ( >=dev-python/sphinx-4.0.1[${PYTHON_USEDEP}] )
	fiona? ( dev-python/fiona[${PYTHON_USEDEP}] )
	geopandas? ( dev-python/geopandas[${PYTHON_USEDEP}] )
	legacy? ( dev-python/importlib-metadata[${PYTHON_USEDEP}] )
	legacy? ( dev-python/importlib-resources[${PYTHON_USEDEP}] )
	network? ( dev-python/networkx[${PYTHON_USEDEP}] )
	pil? ( dev-python/pillow[${PYTHON_USEDEP}] )
	q? ( dev-python/pyside2[${PYTHON_USEDEP}] )
	qgis? ( dev-python/pyside2[${PYTHON_USEDEP}] )
	shapely? ( dev-python/pyproj[${PYTHON_USEDEP}] )
	shapely? ( dev-python/shapely[${PYTHON_USEDEP}] )
	tests? ( dev-python/mock[${PYTHON_USEDEP}] )
	tests? ( >=dev-python/pytest-4.4.1[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
