# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="aws-prototyping-sdk"

HOMEPAGE="https://github.com/aws/aws-prototyping-sdk"
LICENSE="Apache-2.0"
SRC_URI="https://files.pythonhosted.org/packages/1a/0a/a1ce37bfbe8aa35c0e467c6b099d28e0e4fb5560a16cf4d8e53b61f4fb02/aws_prototyping_sdk-${REALVERSION}.tar.gz"
SOURCEFILE="aws_prototyping_sdk-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/aws-cdk-lib[${PYTHON_USEDEP}]
	dev-python/cdk-nag[${PYTHON_USEDEP}]
	dev-python/constructs[${PYTHON_USEDEP}]
	dev-python/jsii[${PYTHON_USEDEP}]
	dev-python/projen[${PYTHON_USEDEP}]
	dev-python/publication[${PYTHON_USEDEP}]
	dev-python/typeguard[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
