# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=wheel

inherit python-r1 gs-pypi

DESCRIPTION="TensorFlow is an open source machine learning framework for everyone. [wheel]"

HOMEPAGE="https://www.tensorflow.org/"
LICENSE="Apache-2.0"
SRC_URI="https://files.pythonhosted.org/packages/cf/99/c7921fb5d1f7bb5d0c4982f14721e1401388d660c178f30fb3c66506c092/${REALNAME//-/_}-${REALVERSION}-py3-none-any.whl"
SOURCEFILE="${REALNAME//-/_}-${REALVERSION}-py3-none-any.whl"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="+bin-wheel"
DEPENDENCIES="dev-python/tf-nightly-macos[${PYTHON_USEDEP}]
	dev-python/tf-nightly-cpu-aws[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
