# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="ccl-scratch-tools"
REALVERSION="0.3.0"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Tools with which to work with Scratch JSON files."

HOMEPAGE="https://github.com/GSE-CCL/scratch-tools"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/21/47/9a33dd8d38bc58bb40be0d92c504d5cbc38df5f6a27a7c4939b2efc5f293/ccl_scratch_tools-${REALVERSION}.tar.gz"
SOURCEFILE="ccl_scratch_tools-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=""
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
