# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Tryton module for Point of Sales"

HOMEPAGE="http://www.tryton.org/"
LICENSE="GPL-3"
SRC_URI="https://files.pythonhosted.org/packages/87/6b/0eee2c7959950c6aafc6d0b7c4f7aaae5873b09891927d7f9debc6d8647a/${REALNAME//-/_}-${REALVERSION}.tar.gz"
SOURCEFILE="_}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="test"
DEPENDENCIES="dev-python/python-sql[${PYTHON_USEDEP}]
	dev-python/trytond-account[${PYTHON_USEDEP}]
	dev-python/trytond-account-product[${PYTHON_USEDEP}]
	dev-python/trytond-company[${PYTHON_USEDEP}]
	dev-python/trytond-party[${PYTHON_USEDEP}]
	dev-python/trytond-product[${PYTHON_USEDEP}]
	dev-python/trytond-sale[${PYTHON_USEDEP}]
	dev-python/trytond-stock[${PYTHON_USEDEP}]
	dev-python/trytond[${PYTHON_USEDEP}]
	test? ( dev-python/proteus[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
