# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="dataclass-wizard"
REALVERSION="0.22.2"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
REPO_URI="http://pypi.python.org/packages/source/${REALNAME:0:1}/${REALNAME}/"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
DISTUTILS_USE_PEP517=standalone

inherit gs-pypi

DESCRIPTION="Marshal dataclasses tofrom JSON. Use field properties with initial values. Construct a dataclass schema with JSON input."

HOMEPAGE="https://github.com/rnag/dataclass-wizard"
LICENSE="Apache 2.0"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="timedelta yaml"
DEPENDENCIES="dev-python/typing-extensions[${PYTHON_USEDEP}]
	dev-python/dataclasses[${PYTHON_USEDEP}]
	dev-python/backports-datetime-fromisoformat[${PYTHON_USEDEP}]
	timedelta? ( dev-python/pytimeparse[${PYTHON_USEDEP}] )
	yaml? ( dev-python/PyYAML[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
