# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Snake is yet another Make-like tool inspired by Rake."

HOMEPAGE="http://yumatov.org/snake/"
LICENSE="UNKNOWN"
SRC_URI="https://files.pythonhosted.org/packages/74/fa/60e007e4858ab4ea5b53acae114769f5b0281e435a6f3a6027622a55ce55/Snake-${REALVERSION}.tar.gz"
SOURCEFILE="Snake-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=""
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
