# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="A lightweight tool for labeling 3D bounding boxes in point clouds."

HOMEPAGE="https://github.com/ch-sa/labelCloud"
LICENSE="GNU General Public License v3.0"
SRC_URI="https://files.pythonhosted.org/packages/d0/85/53eb44d0b9ddd57f598fa90a9c3f9b3333e75ef63c5580af911898127536/labelCloud-${REALVERSION}.tar.gz"
SOURCEFILE="labelCloud-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="tests"
DEPENDENCIES="dev-python/numpy[${PYTHON_USEDEP}]
	dev-python/open3d[${PYTHON_USEDEP}]
	dev-python/PyOpenGL[${PYTHON_USEDEP}]
	dev-python/PyOpenGL-accelerate[${PYTHON_USEDEP}]
	dev-python/PyQt5[${PYTHON_USEDEP}]
	tests? ( dev-python/pytest[${PYTHON_USEDEP}] )
	tests? ( dev-python/pytest-qt[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
