# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Download content from streaming platforms"

HOMEPAGE="https://github.com/Arrowar/StreamingCommunity"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/7f/38/cd3c829cc32fb863af9ebb9808a0b56ffc4f1607402f6077e2693df5d480/streamingcommunity-${REALVERSION}.tar.gz"
SOURCEFILE="streamingcommunity-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=""
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
