# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="A single Package for all the database connectivities  ( E.g : MySQL, MongoDb, Cassandra)"

HOMEPAGE="https://github.com/hrisikesh-neogi/Database-Connect"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/ce/28/726546bfa5254c5f38a341e4164539ca5bce8da823d813b876a7ce839972/database_connect-${REALVERSION}.tar.gz"
SOURCEFILE="database_connect-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/pymongo[${PYTHON_USEDEP}]
	dev-python/pymongo[${PYTHON_USEDEP}]
	dev-python/dnspython[${PYTHON_USEDEP}]
	dev-python/cassandra-driver[${PYTHON_USEDEP}]
	dev-python/pandas[${PYTHON_USEDEP}]
	dev-python/numpy[${PYTHON_USEDEP}]
	dev-python/ensure[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
