# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Nonebot2 成分姬插件"

HOMEPAGE="https://github.com/noneplugin/nonebot-plugin-ddcheck"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/81/0a/201b95bc0646932cd721271ef2281848982d0839739a5b214a9c6721b4f2/nonebot_plugin_ddcheck-${REALVERSION}.tar.gz"
SOURCEFILE="nonebot_plugin_ddcheck-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/nonebot-adapter-onebot[${PYTHON_USEDEP}]
	dev-python/nonebot-plugin-htmlrender[${PYTHON_USEDEP}]
	dev-python/nonebot-plugin-apscheduler[${PYTHON_USEDEP}]
	dev-python/nonebot-plugin-localstore[${PYTHON_USEDEP}]
	dev-python/httpx[${PYTHON_USEDEP}]
	dev-python/Jinja2[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
