# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Freqtrade - Crypto Trading Bot"

HOMEPAGE="https://github.com/freqtrade/freqtrade"
LICENSE="GPL-3"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="all dev freqai freqai-rl hdf5 hyperopt jupyter plot"
DEPENDENCIES=">=dev-python/sqlalchemy-2.0.6[${PYTHON_USEDEP}]
	dev-python/ccxt[${PYTHON_USEDEP}]
	dev-python/python-telegram-bot[${PYTHON_USEDEP}]
	>=dev-python/humanize-4.0.0[${PYTHON_USEDEP}]
	dev-python/cachetools[${PYTHON_USEDEP}]
	dev-python/requests[${PYTHON_USEDEP}]
	>=dev-python/httpx-0.24.1[${PYTHON_USEDEP}]
	dev-python/urllib3[${PYTHON_USEDEP}]
	dev-python/jsonschema[${PYTHON_USEDEP}]
	<dev-python/numpy-2.0[${PYTHON_USEDEP}]
	<dev-python/pandas-3.0[${PYTHON_USEDEP}]
	dev-python/TA-Lib[${PYTHON_USEDEP}]
	dev-python/pandas-ta[${PYTHON_USEDEP}]
	dev-python/technical[${PYTHON_USEDEP}]
	dev-python/tabulate[${PYTHON_USEDEP}]
	dev-python/pycoingecko[${PYTHON_USEDEP}]
	dev-python/py-find-1st[${PYTHON_USEDEP}]
	dev-python/python-rapidjson[${PYTHON_USEDEP}]
	dev-python/orjson[${PYTHON_USEDEP}]
	dev-python/jinja[${PYTHON_USEDEP}]
	dev-python/questionary[${PYTHON_USEDEP}]
	dev-python/prompt-toolkit[${PYTHON_USEDEP}]
	>=dev-python/joblib-1.2.0[${PYTHON_USEDEP}]
	dev-python/rich[${PYTHON_USEDEP}]
	dev-python/fastapi[${PYTHON_USEDEP}]
	>=dev-python/pydantic-2.2.0[${PYTHON_USEDEP}]
	dev-python/pyjwt[${PYTHON_USEDEP}]
	dev-python/websockets[${PYTHON_USEDEP}]
	dev-python/uvicorn[${PYTHON_USEDEP}]
	dev-python/psutil[${PYTHON_USEDEP}]
	dev-python/schedule[${PYTHON_USEDEP}]
	dev-python/janus[${PYTHON_USEDEP}]
	dev-python/ast-comments[${PYTHON_USEDEP}]
	dev-python/aiofiles[${PYTHON_USEDEP}]
	dev-python/aiohttp[${PYTHON_USEDEP}]
	dev-python/cryptography[${PYTHON_USEDEP}]
	dev-python/sdnotify[${PYTHON_USEDEP}]
	dev-python/python-dateutil[${PYTHON_USEDEP}]
	dev-python/pytz[${PYTHON_USEDEP}]
	dev-python/packaging[${PYTHON_USEDEP}]
	dev-python/freqtrade-client[${PYTHON_USEDEP}]
	dev-python/pyarrow[${PYTHON_USEDEP}]
	all? ( >=dev-python/plotly-4.0[${PYTHON_USEDEP}] )
	all? ( dev-python/coveralls[${PYTHON_USEDEP}] )
	all? ( dev-python/isort[${PYTHON_USEDEP}] )
	all? ( dev-python/mypy[${PYTHON_USEDEP}] )
	all? ( dev-python/pre-commit[${PYTHON_USEDEP}] )
	all? ( dev-python/pytest-asyncio[${PYTHON_USEDEP}] )
	all? ( dev-python/pytest-cov[${PYTHON_USEDEP}] )
	all? ( dev-python/pytest-mock[${PYTHON_USEDEP}] )
	all? ( dev-python/pytest-random-order[${PYTHON_USEDEP}] )
	all? ( dev-python/pytest[${PYTHON_USEDEP}] )
	all? ( dev-python/ruff[${PYTHON_USEDEP}] )
	all? ( dev-python/time-machine[${PYTHON_USEDEP}] )
	all? ( dev-python/types-cachetools[${PYTHON_USEDEP}] )
	all? ( dev-python/types-filelock[${PYTHON_USEDEP}] )
	all? ( dev-python/types-python-dateutiltypes-requests[${PYTHON_USEDEP}] )
	all? ( dev-python/types-tabulate[${PYTHON_USEDEP}] )
	all? ( dev-python/jupyter[${PYTHON_USEDEP}] )
	all? ( dev-python/nbstripout[${PYTHON_USEDEP}] )
	all? ( dev-python/ipykernel[${PYTHON_USEDEP}] )
	all? ( dev-python/nbconvert[${PYTHON_USEDEP}] )
	all? ( dev-python/scipy[${PYTHON_USEDEP}] )
	all? ( dev-python/scikit-learn[${PYTHON_USEDEP}] )
	all? ( dev-python/ft-scikit-optimize[${PYTHON_USEDEP}] )
	all? ( dev-python/filelock[${PYTHON_USEDEP}] )
	all? ( dev-python/tables[${PYTHON_USEDEP}] )
	all? ( dev-python/blosc[${PYTHON_USEDEP}] )
	all? ( dev-python/joblib[${PYTHON_USEDEP}] )
	all? ( dev-python/lightgbm[${PYTHON_USEDEP}] )
	all? ( dev-python/xgboost[${PYTHON_USEDEP}] )
	all? ( dev-python/tensorboard[${PYTHON_USEDEP}] )
	all? ( dev-python/datasieve[${PYTHON_USEDEP}] )
	all? ( dev-python/torch[${PYTHON_USEDEP}] )
	all? ( dev-python/gymnasium[${PYTHON_USEDEP}] )
	all? ( dev-python/stable-baselines3[${PYTHON_USEDEP}] )
	all? ( dev-python/sb3-contrib[${PYTHON_USEDEP}] )
	all? ( dev-python/tqdm[${PYTHON_USEDEP}] )
	all? ( dev-python/catboost[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/plotly-4.0[${PYTHON_USEDEP}] )
	dev? ( dev-python/coveralls[${PYTHON_USEDEP}] )
	dev? ( dev-python/isort[${PYTHON_USEDEP}] )
	dev? ( dev-python/mypy[${PYTHON_USEDEP}] )
	dev? ( dev-python/pre-commit[${PYTHON_USEDEP}] )
	dev? ( dev-python/pytest-asyncio[${PYTHON_USEDEP}] )
	dev? ( dev-python/pytest-cov[${PYTHON_USEDEP}] )
	dev? ( dev-python/pytest-mock[${PYTHON_USEDEP}] )
	dev? ( dev-python/pytest-random-order[${PYTHON_USEDEP}] )
	dev? ( dev-python/pytest[${PYTHON_USEDEP}] )
	dev? ( dev-python/ruff[${PYTHON_USEDEP}] )
	dev? ( dev-python/time-machine[${PYTHON_USEDEP}] )
	dev? ( dev-python/types-cachetools[${PYTHON_USEDEP}] )
	dev? ( dev-python/types-filelock[${PYTHON_USEDEP}] )
	dev? ( dev-python/types-python-dateutiltypes-requests[${PYTHON_USEDEP}] )
	dev? ( dev-python/types-tabulate[${PYTHON_USEDEP}] )
	dev? ( dev-python/jupyter[${PYTHON_USEDEP}] )
	dev? ( dev-python/nbstripout[${PYTHON_USEDEP}] )
	dev? ( dev-python/ipykernel[${PYTHON_USEDEP}] )
	dev? ( dev-python/nbconvert[${PYTHON_USEDEP}] )
	dev? ( dev-python/scipy[${PYTHON_USEDEP}] )
	dev? ( dev-python/scikit-learn[${PYTHON_USEDEP}] )
	dev? ( dev-python/ft-scikit-optimize[${PYTHON_USEDEP}] )
	dev? ( dev-python/filelock[${PYTHON_USEDEP}] )
	dev? ( dev-python/tables[${PYTHON_USEDEP}] )
	dev? ( dev-python/blosc[${PYTHON_USEDEP}] )
	dev? ( dev-python/joblib[${PYTHON_USEDEP}] )
	dev? ( dev-python/lightgbm[${PYTHON_USEDEP}] )
	dev? ( dev-python/xgboost[${PYTHON_USEDEP}] )
	dev? ( dev-python/tensorboard[${PYTHON_USEDEP}] )
	dev? ( dev-python/datasieve[${PYTHON_USEDEP}] )
	dev? ( dev-python/torch[${PYTHON_USEDEP}] )
	dev? ( dev-python/gymnasium[${PYTHON_USEDEP}] )
	dev? ( dev-python/stable-baselines3[${PYTHON_USEDEP}] )
	dev? ( dev-python/sb3-contrib[${PYTHON_USEDEP}] )
	dev? ( dev-python/tqdm[${PYTHON_USEDEP}] )
	dev? ( dev-python/catboost[${PYTHON_USEDEP}] )
	freqai? ( dev-python/scikit-learn[${PYTHON_USEDEP}] )
	freqai? ( dev-python/joblib[${PYTHON_USEDEP}] )
	freqai? ( dev-python/lightgbm[${PYTHON_USEDEP}] )
	freqai? ( dev-python/xgboost[${PYTHON_USEDEP}] )
	freqai? ( dev-python/tensorboard[${PYTHON_USEDEP}] )
	freqai? ( dev-python/datasieve[${PYTHON_USEDEP}] )
	freqai? ( dev-python/catboost[${PYTHON_USEDEP}] )
	freqai-rl? ( dev-python/torch[${PYTHON_USEDEP}] )
	freqai-rl? ( dev-python/gymnasium[${PYTHON_USEDEP}] )
	freqai-rl? ( dev-python/stable-baselines3[${PYTHON_USEDEP}] )
	freqai-rl? ( dev-python/sb3-contrib[${PYTHON_USEDEP}] )
	freqai-rl? ( dev-python/tqdm[${PYTHON_USEDEP}] )
	hdf5? ( dev-python/tables[${PYTHON_USEDEP}] )
	hdf5? ( dev-python/blosc[${PYTHON_USEDEP}] )
	hyperopt? ( dev-python/scipy[${PYTHON_USEDEP}] )
	hyperopt? ( dev-python/scikit-learn[${PYTHON_USEDEP}] )
	hyperopt? ( dev-python/ft-scikit-optimize[${PYTHON_USEDEP}] )
	hyperopt? ( dev-python/filelock[${PYTHON_USEDEP}] )
	jupyter? ( dev-python/jupyter[${PYTHON_USEDEP}] )
	jupyter? ( dev-python/nbstripout[${PYTHON_USEDEP}] )
	jupyter? ( dev-python/ipykernel[${PYTHON_USEDEP}] )
	jupyter? ( dev-python/nbconvert[${PYTHON_USEDEP}] )
	plot? ( >=dev-python/plotly-4.0[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
