# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="phishme-intelligence"
REALVERSION="4.8.0"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="PhishMe Intelligence Integration Library"

HOMEPAGE="https://www.threathq.com/documentation/display/MAD"
LICENSE="Proprietary"
SRC_URI="https://files.pythonhosted.org/packages/ac/98/dc7952c7a0f994e6b54e71fb6468b3045f6fe3c5bdc2006d73d6094fb10b/phishme_intelligence-${REALVERSION}.tar.gz"
SOURCEFILE="phishme_intelligence-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=""
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
