# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="pyqode3-language-server"
REALVERSION="0.1.14"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Adds language-server support to pyqode.core"

HOMEPAGE="https://github.com/open-cogsci/pyqode.language_server"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/30/89/728e92d81e106a06143328ad425382963b70ab2251668503dbc43df5bd41/pyqode3.language_server-${REALVERSION}.tar.gz"
SOURCEFILE="pyqode3.language_server-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=""
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
