# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=wheel

inherit python-r1 gs-pypi

DESCRIPTION="Python bindings for the QuantLib library [wheel]"

HOMEPAGE="https://www.quantlib.org"
LICENSE="BSD 3-Clause"
SRC_URI="https://files.pythonhosted.org/packages/8e/c8/9d1764f7378003a72f057251eb0e9b71d69218b17fa76c10faf7203ce0a6/quantlib-${REALVERSION}-cp314-cp314t-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl"
SOURCEFILE="quantlib-${REALVERSION}-cp314-cp314t-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="virtual/allow-pypi-wheels"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
