# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="2.1.1.9.dev202507041750843886"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=wheel

inherit python-r1 gs-pypi

DESCRIPTION="Bayesian networks and other Probabilistic Graphical Models. [wheel]"

HOMEPAGE="https://agrum.gitlab.io/"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/7a/05/dbd816c9625d1b5d5ddcc680c650d6ba86bb683331c083d7466b52f490d0/pyagrum_nightly-${REALVERSION}-cp310-abi3-manylinux2014_x86_64.whl"
SOURCEFILE="pyagrum_nightly-${REALVERSION}-cp310-abi3-manylinux2014_x86_64.whl"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/numpy[${PYTHON_USEDEP}]
	dev-python/matplotlib[${PYTHON_USEDEP}]
	dev-python/pydot[${PYTHON_USEDEP}]
	virtual/allow-pypi-wheels"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
