# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=wheel

inherit python-r1 gs-pypi

DESCRIPTION="BLD for Python [wheel]"

HOMEPAGE="http://www.rim.cyric.tohoku.ac.jp/pybld/pybld.html"
LICENSE="GNU Library General Public License GPL Version 2"
SRC_URI="https://files.pythonhosted.org/packages/9f/25/3fccabbe20fe0b0ea506b2fde98a27fafdc3266828d481ab31f063f40f4d/pybld-${REALVERSION}-cp313-cp313-manylinux1_x86_64.whl"
SOURCEFILE="pybld-${REALVERSION}-cp313-cp313-manylinux1_x86_64.whl"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="virtual/allow-pypi-wheels"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
