# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="talisker"
REALVERSION="0.21.3"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="A common WSGI stack"

HOMEPAGE="https://github.com/canonical-ols/talisker"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/source/t/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="celery dev django flask gevent gunicorn pg prometheus raven"
DEPENDENCIES="dev-python/requests[${PYTHON_USEDEP}]
	dev-python/Werkzeug[${PYTHON_USEDEP}]
	dev-python/statsd[${PYTHON_USEDEP}]
	celery? ( dev-python/celery[${PYTHON_USEDEP}] )
	dev? ( dev-python/logging-tree[${PYTHON_USEDEP}] )
	dev? ( dev-python/pygments[${PYTHON_USEDEP}] )
	dev? ( dev-python/psutil[${PYTHON_USEDEP}] )
	dev? ( dev-python/objgraph[${PYTHON_USEDEP}] )
	django? ( dev-python/django[${PYTHON_USEDEP}] )
	flask? ( dev-python/flask[${PYTHON_USEDEP}] )
	flask? ( dev-python/blinker[${PYTHON_USEDEP}] )
	gevent? ( dev-python/gevent[${PYTHON_USEDEP}] )
	gunicorn? ( dev-python/gunicorn[${PYTHON_USEDEP}] )
	pg? ( dev-python/sqlparse[${PYTHON_USEDEP}] )
	pg? ( dev-python/psycopg2[${PYTHON_USEDEP}] )
	prometheus? ( dev-python/prometheus-client[${PYTHON_USEDEP}] )
	raven? ( dev-python/raven[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
