# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="A tool to mirror Debian repositories for use as a local mirror."

HOMEPAGE="https://github.com/Progeny42/Refrapt"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/fa/68/58cbfc8ae4d23ab4b47e29e54af5b1f7d40c6794564bdc1f1ade7efc6716/Refrapt-${REALVERSION}.tar.gz"
SOURCEFILE="Refrapt-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/Click[${PYTHON_USEDEP}]
	dev-python/Colorama[${PYTHON_USEDEP}]
	dev-python/tqdm[${PYTHON_USEDEP}]
	dev-python/wget[${PYTHON_USEDEP}]
	dev-python/filelock[${PYTHON_USEDEP}]
	dev-python/tendo[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
