# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="VividHues: Super light Python string formatter!"

HOMEPAGE="https://github.com/KennyOliver/VividHues"
LICENSE="AGPL-3"
SRC_URI="https://files.pythonhosted.org/packages/88/06/cecfcd2f0d7eac68f2ce0ba126bf6f94d03424f1447137fbe0eab7477e42/VividHues-${REALVERSION}.tar.gz"
SOURCEFILE="VividHues-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=""
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
