# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Run commands on multiple hosts via SSH"

HOMEPAGE="https://github.com/yufei-pan/multiSSH3"
LICENSE="GPL-3+"
SRC_URI="https://files.pythonhosted.org/packages/04/1e/37def60ec031bda6e7268ffedae0d3e53f64d354049a45c458b000665b6d/multissh3-${REALVERSION}.tar.gz"
SOURCEFILE="multissh3-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/argparse[${PYTHON_USEDEP}]
	dev-python/ipaddress[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
