# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Get information about your Letterboxd activity."

HOMEPAGE="https://github.com/mBaratta96/letterboxd_stats"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME//-/_}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME//-/_}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/ascii-magic[${PYTHON_USEDEP}]
	dev-python/inquirerpy[${PYTHON_USEDEP}]
	~dev-python/lxml-4.9.0[${PYTHON_USEDEP}]
	~dev-python/pandas-2.2.1[${PYTHON_USEDEP}]
	dev-python/pandarallel[${PYTHON_USEDEP}]
	~dev-python/platformdirs-3.0.0[${PYTHON_USEDEP}]
	~dev-python/requests-2.31.0[${PYTHON_USEDEP}]
	~dev-python/rich-13.3.5[${PYTHON_USEDEP}]
	dev-python/tmdbv3api[${PYTHON_USEDEP}]
	~dev-python/tomli-2.0.1[${PYTHON_USEDEP}]
	~dev-python/tqdm-4.65.0[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
