# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="async-pixiv"
REALVERSION="0.3.6"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Async Pixiv API"

HOMEPAGE="https://github.com/ArkoClub/async-pixiv"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/c5/a1/7a31774df9f206e38f6222e1ec30dbbbe7475063a7eb12d8a9fc810ca2ed/async_pixiv-${REALVERSION}.tar.gz"
SOURCEFILE="async_pixiv-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="extra full playwright regex ujson"
DEPENDENCIES="dev-python/pydantic[${PYTHON_USEDEP}]
	dev-python/aiohttp-socks[${PYTHON_USEDEP}]
	dev-python/arko-wrapper[${PYTHON_USEDEP}]
	regex? ( dev-python/regex[${PYTHON_USEDEP}] )
	extra? ( dev-python/regex[${PYTHON_USEDEP}] )
	full? ( dev-python/regex[${PYTHON_USEDEP}] )
	ujson? ( dev-python/ujson[${PYTHON_USEDEP}] )
	extra? ( dev-python/ujson[${PYTHON_USEDEP}] )
	full? ( dev-python/ujson[${PYTHON_USEDEP}] )
	extra? ( dev-python/uvloop[${PYTHON_USEDEP}] )
	full? ( dev-python/uvloop[${PYTHON_USEDEP}] )
	playwright? ( dev-python/playwright[${PYTHON_USEDEP}] )
	full? ( dev-python/playwright[${PYTHON_USEDEP}] )
	dev-python/aiofiles[${PYTHON_USEDEP}]
	dev-python/httpx[${PYTHON_USEDEP}]
	dev-python/aiolimiter[${PYTHON_USEDEP}]
	dev-python/pyee[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
