# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Several two-samples tests for count data"

HOMEPAGE="https://github.com/alonkipnis/TwoSampleHC"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/f2/9c/88a25c819ed6ab241abeff8a2113f9ddeb601c741e10bed6e912dac8a3af/twosamplehc-${REALVERSION}.tar.gz"
SOURCEFILE="twosamplehc-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=">=dev-python/numpy-1.6[${PYTHON_USEDEP}]
	dev-python/scipy[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
