# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="bowtie-json-schema"
REALVERSION="0.83.0"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="A meta-validator for the JSON Schema specification."

HOMEPAGE="https://github.com/bowtie-json-schema/bowtie"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/8c/f9/ea04074e3121ea4f17d3e223389512c9f780af854f822cd76873b417e5b2/bowtie_json_schema-${REALVERSION}.tar.gz"
SOURCEFILE="bowtie_json_schema-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/aiodocker[${PYTHON_USEDEP}]
	dev-python/attrs[${PYTHON_USEDEP}]
	dev-python/click[${PYTHON_USEDEP}]
	dev-python/github3-py[${PYTHON_USEDEP}]
	dev-python/jinja2[${PYTHON_USEDEP}]
	dev-python/jsonschema[${PYTHON_USEDEP}]
	dev-python/rich[${PYTHON_USEDEP}]
	dev-python/structlog[${PYTHON_USEDEP}]
	dev-python/typing-extensions[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
