# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="A triplestore wrapper for Python."

HOMEPAGE=""
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="dev docs pre-commit testing testing-core"
DEPENDENCIES="dev-python/Pint[${PYTHON_USEDEP}]
	dev? ( dev-python/mike[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/mkdocs-1.5[${PYTHON_USEDEP}] )
	dev? ( dev-python/mkdocs-awesome-pages-plugin[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/mkdocs-material-9.5.5[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/mkdocstrings-0.22.0[${PYTHON_USEDEP}] )
	dev? ( dev-python/pre-commit[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/pylint-2.13[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/pytest-7.4[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/pytest-cov-4.1[${PYTHON_USEDEP}] )
	dev? ( dev-python/EMMOntoPy[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/rdflib-6.3[${PYTHON_USEDEP}] )
	dev? ( dev-python/SPARQLWrapper[${PYTHON_USEDEP}] )
	dev? ( dev-python/DLite-Python[${PYTHON_USEDEP}] )
	docs? ( dev-python/mike[${PYTHON_USEDEP}] )
	docs? ( ~dev-python/mkdocs-1.5[${PYTHON_USEDEP}] )
	docs? ( dev-python/mkdocs-awesome-pages-plugin[${PYTHON_USEDEP}] )
	docs? ( >=dev-python/mkdocs-material-9.5.5[${PYTHON_USEDEP}] )
	docs? ( ~dev-python/mkdocstrings-0.22.0[${PYTHON_USEDEP}] )
	docs? ( dev-python/EMMOntoPy[${PYTHON_USEDEP}] )
	docs? ( ~dev-python/rdflib-6.3[${PYTHON_USEDEP}] )
	docs? ( dev-python/SPARQLWrapper[${PYTHON_USEDEP}] )
	docs? ( dev-python/DLite-Python[${PYTHON_USEDEP}] )
	pre-commit? ( dev-python/pre-commit[${PYTHON_USEDEP}] )
	pre-commit? ( ~dev-python/pylint-2.13[${PYTHON_USEDEP}] )
	testing? ( ~dev-python/pytest-7.4[${PYTHON_USEDEP}] )
	testing? ( ~dev-python/pytest-cov-4.1[${PYTHON_USEDEP}] )
	testing? ( dev-python/EMMOntoPy[${PYTHON_USEDEP}] )
	testing? ( ~dev-python/rdflib-6.3[${PYTHON_USEDEP}] )
	testing? ( dev-python/SPARQLWrapper[${PYTHON_USEDEP}] )
	testing? ( dev-python/DLite-Python[${PYTHON_USEDEP}] )
	testing? ( ~dev-python/graphviz-0.20[${PYTHON_USEDEP}] )
	testing? ( dev-python/Pint[${PYTHON_USEDEP}] )
	testing-core? ( ~dev-python/pytest-7.4[${PYTHON_USEDEP}] )
	testing-core? ( ~dev-python/pytest-cov-4.1[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
