# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=wheel

inherit python-r1 gs-pypi

DESCRIPTION="Utility for managing metadata. [wheel]"

HOMEPAGE="https://github.com/Drakovek/MetadataMagic"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/5c/6a/6cdd5ffc68815bd740b3136a3419e09b0af54d5ab4bd2dfa4484722d0607/metadata_magic-${REALVERSION}-py3-none-any.whl"
SOURCEFILE="metadata_magic-${REALVERSION}-py3-none-any.whl"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/covergenerator[${PYTHON_USEDEP}]
	>=dev-python/html5lib-1.1[${PYTHON_USEDEP}]
	dev-python/html-string-tools[${PYTHON_USEDEP}]
	>=dev-python/pillow-8.0.0[${PYTHON_USEDEP}]
	dev-python/python-print-tools[${PYTHON_USEDEP}]
	dev-python/python-ffmpeg[${PYTHON_USEDEP}]
	>=dev-python/tqdm-4.64.1[${PYTHON_USEDEP}]
	virtual/allow-pypi-wheels"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
