# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Serve click scripts over the web with minimal effort."

HOMEPAGE="https://github.com/fredrik-corneliusson/click-web"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME//-/_}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME//-/_}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="dev"
DEPENDENCIES=">=dev-python/click-8.0[${PYTHON_USEDEP}]
	>=dev-python/flask-2.3.2[${PYTHON_USEDEP}]
	dev-python/jinja[${PYTHON_USEDEP}]
	dev-python/Flask-HTTPAuth[${PYTHON_USEDEP}]
	dev? ( >=dev-python/pytest-6.2[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/flake8-3.9[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/beautifulsoup4-4.9[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/isort-5.8[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/twine-3.4[${PYTHON_USEDEP}] )
	dev? ( dev-python/wheel[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
