# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="4dgb-workflow"
REALVERSION="1.5.6"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="4D Genome Browser Workflow."

HOMEPAGE="https://github.com/4dgb/4DGBWorkflow"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/source/4/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=""
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
