# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="报名模块"

HOMEPAGE=""
LICENSE="apache 3.0"
SRC_URI="https://files.pythonhosted.org/packages/86/5b/87844d4d2c7b7e882ae0e84bde7db901b2a1a2e0c519570e9a12d382aed0/xj_enroll-${REALVERSION}.tar.gz"
SOURCEFILE="xj_enroll-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=""
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
