# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="A PySpark package used to expedite and standardise the data linkage process"

HOMEPAGE="https://github.com/Data-Linkage/dlh_utils"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/87/8d/043a77988d5e5ae0bca11f6de06869ef2e247b5e03aedbdc261d9720e002/dlh_utils-${REALVERSION}.tar.gz"
SOURCEFILE="dlh_utils-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/graphframes[${PYTHON_USEDEP}]
	dev-python/graphframes-jars[${PYTHON_USEDEP}]
	dev-python/jellyfish[${PYTHON_USEDEP}]
	dev-python/pandas[${PYTHON_USEDEP}]
	dev-python/importlib_metadata[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
