# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="2.0.0rc8"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=wheel

inherit python-r1 gs-pypi

DESCRIPTION="Python interface to PartMC [wheel]"

HOMEPAGE=""
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/1c/04/f141ec0b38125860e390fc6f5e13490d0cf4d6cb7e6a89a512294adea25e/pypartmc-${REALVERSION}-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
SOURCEFILE="pypartmc-${REALVERSION}-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="examples tests"
DEPENDENCIES="dev-python/numpy[${PYTHON_USEDEP}]
	dev-python/nanobind[${PYTHON_USEDEP}]
	tests? ( dev-python/pytest[${PYTHON_USEDEP}] )
	tests? ( dev-python/pytest-order[${PYTHON_USEDEP}] )
	examples? ( >dev-python/matplotlib-3.10.0[${PYTHON_USEDEP}] )
	examples? ( dev-python/ipywidgets[${PYTHON_USEDEP}] )
	examples? ( dev-python/voila[${PYTHON_USEDEP}] )
	examples? ( dev-python/open-atmos-jupyter-utils[${PYTHON_USEDEP}] )
	examples? ( dev-python/PySDM[${PYTHON_USEDEP}] )
	examples? ( dev-python/PyMieScatt[${PYTHON_USEDEP}] )
	examples? ( dev-python/scipy[${PYTHON_USEDEP}] )
	examples? ( dev-python/dustpy[${PYTHON_USEDEP}] )
	virtual/allow-pypi-wheels"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
