# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Python wrapper for the DoorBird LAN API"

HOMEPAGE="https://gitlab.com/klikini/doorbirdpy"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/70/54/b4ded0424586f78a6dbe0d95af23f0e1d06f081ba1036e66593ce53ee82e/doorbirdpy-${REALVERSION}.tar.gz"
SOURCEFILE="doorbirdpy-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/aiohttp[${PYTHON_USEDEP}]
	~dev-python/tenacity-9.0.0[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
