# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="CFFI bindings for LibRaw"

HOMEPAGE="https://github.com/Julian/libraw-cffi"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/4e/39/2053522dae1f00bc69475107424eca6d16932024963b8c361a92474a1651/libraw_cffi-${REALVERSION}.tar.gz"
SOURCEFILE="libraw_cffi-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=""
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
