# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="django-seeker"
REALVERSION="7.3.0"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="A python package for mapping and querying Django models in Elasticsearch/OpenSearch."

HOMEPAGE="https://github.com/imsweb/django-seeker"
LICENSE="BSD"
SRC_URI="https://files.pythonhosted.org/packages/source/d/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/elasticsearch-dsl[${PYTHON_USEDEP}]
	dev-python/opensearch-dsl[${PYTHON_USEDEP}]
	dev-python/snowballstemmer[${PYTHON_USEDEP}]
	dev-python/bleach[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
