# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="vulcan-athena"
REALVERSION="0.2.6"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Python packaging for Athena's reporting framework"

HOMEPAGE="https://github.com/mehulnagpurkar/vulcan_athena"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/33/f4/e656f4c3d4de6787cacde58697eda6ed1a8574eacc492fcece44342455c6/vulcan_athena-${REALVERSION}.tar.gz"
SOURCEFILE="vulcan_athena-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=""
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
