# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Social Business platform (entreprise collaboration and information management)"

HOMEPAGE="https://github.com/abilian/abilian-sbe"
LICENSE="LGPL-2.0-or-later"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/abilian-core[${PYTHON_USEDEP}]
	dev-python/chardet[${PYTHON_USEDEP}]
	<dev-python/flask-babel-2.0[${PYTHON_USEDEP}]
	<dev-python/html2text-2021.0.0[${PYTHON_USEDEP}]
	<dev-python/itsdangerous-2.0[${PYTHON_USEDEP}]
	dev-python/jinja2[${PYTHON_USEDEP}]
	dev-python/langid[${PYTHON_USEDEP}]
	<dev-python/markdown-4.0[${PYTHON_USEDEP}]
	<dev-python/openpyxl-3.0.0[${PYTHON_USEDEP}]
	dev-python/toolz[${PYTHON_USEDEP}]
	dev-python/validate_email[${PYTHON_USEDEP}]
	<dev-python/wtforms-2.2[${PYTHON_USEDEP}]
	dev-python/xlwt[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
