# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Astronomical data analysis development leveraging the Jupyter platform"

HOMEPAGE="https://jdaviz.readthedocs.io/en/latest/"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="all docs roman test"
DEPENDENCIES="dev-python/packaging[${PYTHON_USEDEP}]
	dev-python/astropy[${PYTHON_USEDEP}]
	dev-python/matplotlib[${PYTHON_USEDEP}]
	>=dev-python/traitlets-5.0.5[${PYTHON_USEDEP}]
	dev-python/bqplot[${PYTHON_USEDEP}]
	dev-python/bqplot-image-gl[${PYTHON_USEDEP}]
	dev-python/glue-core[${PYTHON_USEDEP}]
	dev-python/glue-jupyter[${PYTHON_USEDEP}]
	dev-python/echo[${PYTHON_USEDEP}]
	>=dev-python/ipykernel-6.19.4[${PYTHON_USEDEP}]
	dev-python/ipyvue[${PYTHON_USEDEP}]
	dev-python/ipyvuetify[${PYTHON_USEDEP}]
	dev-python/ipysplitpanes[${PYTHON_USEDEP}]
	dev-python/ipygoldenlayout[${PYTHON_USEDEP}]
	>=dev-python/ipywidgets-8.0.6[${PYTHON_USEDEP}]
	dev-python/voila[${PYTHON_USEDEP}]
	>=dev-python/pyyaml-5.4.1[${PYTHON_USEDEP}]
	dev-python/specutils[${PYTHON_USEDEP}]
	dev-python/specreduce[${PYTHON_USEDEP}]
	dev-python/photutils[${PYTHON_USEDEP}]
	dev-python/glue-astronomy[${PYTHON_USEDEP}]
	>=dev-python/asteval-0.9.23[${PYTHON_USEDEP}]
	dev-python/idna[${PYTHON_USEDEP}]
	dev-python/vispy[${PYTHON_USEDEP}]
	dev-python/asdf[${PYTHON_USEDEP}]
	dev-python/stdatamodels[${PYTHON_USEDEP}]
	dev-python/gwcs[${PYTHON_USEDEP}]
	dev-python/regions[${PYTHON_USEDEP}]
	dev-python/scikit-image[${PYTHON_USEDEP}]
	dev-python/sidecar[${PYTHON_USEDEP}]
	dev-python/ipypopout[${PYTHON_USEDEP}]
	dev-python/astroquery[${PYTHON_USEDEP}]
	all? ( dev-python/opencv-python[${PYTHON_USEDEP}] )
	all? ( dev-python/pysiaf[${PYTHON_USEDEP}] )
	docs? ( dev-python/sphinx-astropy[${PYTHON_USEDEP}] )
	docs? ( dev-python/sphinx-design[${PYTHON_USEDEP}] )
	roman? ( dev-python/roman-datamodels[${PYTHON_USEDEP}] )
	test? ( dev-python/pytest[${PYTHON_USEDEP}] )
	test? ( dev-python/pytest-astropy[${PYTHON_USEDEP}] )
	test? ( dev-python/pytest-tornasync[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
