# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Bundle of Perceval backends for Weblate."

HOMEPAGE="https://chaoss.github.io/grimoirelab/"
LICENSE="GPL-3+"
SRC_URI="https://files.pythonhosted.org/packages/39/cc/d44966ca28f2954f220e6b7d57066d6e24d50f6ceaabb1c33a1646d5032b/perceval_weblate-${REALVERSION}.tar.gz"
SOURCEFILE="perceval_weblate-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/requests[${PYTHON_USEDEP}]
	dev-python/grimoirelab-toolkit[${PYTHON_USEDEP}]
	dev-python/perceval[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
