# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION=""

HOMEPAGE=""
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/dd/80/d86257b6272eaba83590f396706f2aa3d8c0cb01004dcdb677be7216b52a/${REALNAME//-/_}-${REALVERSION}.tar.gz"
SOURCEFILE="_}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="cli dask-image itk test"
DEPENDENCIES="dev-python/dask[${PYTHON_USEDEP}]
	dev-python/numpy[${PYTHON_USEDEP}]
	dev-python/platformdirs[${PYTHON_USEDEP}]
	dev-python/psutil[${PYTHON_USEDEP}]
	dev-python/rich[${PYTHON_USEDEP}]
	dev-python/typing-extensions[${PYTHON_USEDEP}]
	dev-python/zarr[${PYTHON_USEDEP}]
	cli? ( dev-python/dask-image[${PYTHON_USEDEP}] )
	cli? ( dev-python/dask[${PYTHON_USEDEP}] )
	cli? ( dev-python/imageio[${PYTHON_USEDEP}] )
	cli? ( dev-python/itk-filtering[${PYTHON_USEDEP}] )
	cli? ( dev-python/itk-io[${PYTHON_USEDEP}] )
	cli? ( dev-python/tifffile[${PYTHON_USEDEP}] )
	dask-image? ( dev-python/dask-image[${PYTHON_USEDEP}] )
	itk? ( dev-python/itk-filtering[${PYTHON_USEDEP}] )
	test? ( dev-python/itk-filtering[${PYTHON_USEDEP}] )
	test? ( dev-python/itk-io[${PYTHON_USEDEP}] )
	test? ( dev-python/itkwasm[${PYTHON_USEDEP}] )
	test? ( dev-python/pooch[${PYTHON_USEDEP}] )
	test? ( dev-python/pytest[${PYTHON_USEDEP}] )
	test? ( dev-python/tifffile[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
