# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="schema-validator"
REALVERSION="0.2.5"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="A flask/quart extension to provide schema validation with pydantic."

HOMEPAGE="https://github.com/huangxiaohen2738/schema-validator"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/57/ab/fdaca277af898bb228e9e228a639bc8df2649814b67a0bdff9f223bd1bf0/schema_validator-${REALVERSION}.tar.gz"
SOURCEFILE="schema_validator-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/pyhumps[${PYTHON_USEDEP}]
	dev-python/pydantic[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
