# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="2023.4.0b2"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Wallaroo.ai model management API client [top-max 2024.2.1]"

HOMEPAGE="https://www.wallaroo.ai/"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="~dev-python/appdirs-1.4.4[${PYTHON_USEDEP}]
	>=dev-python/attrs-21.3.0[${PYTHON_USEDEP}]
	dev-python/gql[${PYTHON_USEDEP}]
	<dev-python/httpx-0.24.0[${PYTHON_USEDEP}]
	~dev-python/ipython-7.24.1[${PYTHON_USEDEP}]
	~dev-python/matplotlib-3.5.0[${PYTHON_USEDEP}]
	~dev-python/numpy-1.22.3[${PYTHON_USEDEP}]
	~dev-python/orjson-3.8.0[${PYTHON_USEDEP}]
	~dev-python/pandas-1.3.4[${PYTHON_USEDEP}]
	~dev-python/pyarrow-12.0.1[${PYTHON_USEDEP}]
	~dev-python/pyjwt-2.4.0[${PYTHON_USEDEP}]
	~dev-python/python-dateutil-2.8.2[${PYTHON_USEDEP}]
	~dev-python/pyyaml-6.0[${PYTHON_USEDEP}]
	<dev-python/requests-toolbelt-1.0[${PYTHON_USEDEP}]
	~dev-python/requests-2.25.1[${PYTHON_USEDEP}]
	~dev-python/scipy-1.8.0[${PYTHON_USEDEP}]
	~dev-python/seaborn-0.11.2[${PYTHON_USEDEP}]
	~dev-python/tenacity-8.0.1[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
