# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="0.5.2.dev1"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="File based cache for resources and metadata"

HOMEPAGE="https://github.com/epiviz/pyBiocFileCache"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/2f/ea/28d4d98d284dd9aaa4094efccb55c981f974df00baa86def568cc7f53b2e/pybiocfilecache-${REALVERSION}.tar.gz"
SOURCEFILE="pybiocfilecache-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="testing"
DEPENDENCIES="dev-python/sqlalchemy[${PYTHON_USEDEP}]
	testing? ( dev-python/setuptools[${PYTHON_USEDEP}] )
	testing? ( dev-python/pytest[${PYTHON_USEDEP}] )
	testing? ( dev-python/pytest-cov[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
