# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Flask + MongoDB Web CMS for Developers."

HOMEPAGE="https://github.com/paranoid-software/elemental-cms"
LICENSE="MPL-2.0"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/Flask[${PYTHON_USEDEP}]
	~dev-python/pycountry-20.7.3[${PYTHON_USEDEP}]
	>=dev-python/pymongo-3.12.1[${PYTHON_USEDEP}]
	dev-python/cloup[${PYTHON_USEDEP}]
	~dev-python/deepdiff-5.6.0[${PYTHON_USEDEP}]
	dev-python/Flask-Babel[${PYTHON_USEDEP}]
	dev-python/google-cloud-storage[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
