# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Rucio Package"

HOMEPAGE="https://rucio.cern.ch/"
LICENSE="Apache-2.0"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="dev elastic globus kerberos mongo mysql oracle postgresql saml"
DEPENDENCIES="<=dev-python/requests-2.32.3[${PYTHON_USEDEP}]
	<=dev-python/urllib3-1.26.19[${PYTHON_USEDEP}]
	<=dev-python/dogpile-cache-1.2.2[${PYTHON_USEDEP}]
	<=dev-python/packaging-24.1[${PYTHON_USEDEP}]
	<=dev-python/tabulate-0.9.0[${PYTHON_USEDEP}]
	<=dev-python/jsonschema-4.23.0[${PYTHON_USEDEP}]
	<=dev-python/rich-13.9.4[${PYTHON_USEDEP}]
	<=dev-python/typing-extensions-4.12.2[${PYTHON_USEDEP}]
	<=dev-python/argcomplete-3.5.3[${PYTHON_USEDEP}]
	dev-python/boto[${PYTHON_USEDEP}]
	<=dev-python/python-magic-0.4.27[${PYTHON_USEDEP}]
	<=dev-python/paramiko-3.5.1[${PYTHON_USEDEP}]
	<=dev-python/boto3-1.37.5[${PYTHON_USEDEP}]
	<=dev-python/sqlalchemy-2.0.38[${PYTHON_USEDEP}]
	<=dev-python/alembic-1.14.1[${PYTHON_USEDEP}]
	dev-python/pymemcache[${PYTHON_USEDEP}]
	<=dev-python/python-dateutil-2.9.0_p0[${PYTHON_USEDEP}]
	<=dev-python/stomp-py-8.2.0[${PYTHON_USEDEP}]
	<=dev-python/statsd-4.0.1[${PYTHON_USEDEP}]
	dev-python/geoip2[${PYTHON_USEDEP}]
	<=dev-python/google-auth-2.38.0[${PYTHON_USEDEP}]
	<=dev-python/redis-5.2.1[${PYTHON_USEDEP}]
	<=dev-python/flask-3.1.0[${PYTHON_USEDEP}]
	dev-python/oic[${PYTHON_USEDEP}]
	<=dev-python/prometheus-client-0.21.1[${PYTHON_USEDEP}]
	oracle? ( dev-python/oracledb[${PYTHON_USEDEP}] )
	mongo? ( <=dev-python/pymongo-4.11.2[${PYTHON_USEDEP}] )
	elastic? ( <=dev-python/elasticsearch-8.15.1[${PYTHON_USEDEP}] )
	postgresql? ( <=dev-python/psycopg-3.2.3[${PYTHON_USEDEP}] )
	postgresql? ( dev-python/psycopg-binary[${PYTHON_USEDEP}] )
	postgresql? ( dev-python/psycopg-pool[${PYTHON_USEDEP}] )
	mysql? ( <=dev-python/pymysql-1.1.1[${PYTHON_USEDEP}] )
	kerberos? ( <=dev-python/kerberos-1.3.1[${PYTHON_USEDEP}] )
	kerberos? ( dev-python/pykerberos[${PYTHON_USEDEP}] )
	kerberos? ( <=dev-python/requests-kerberos-0.15.0[${PYTHON_USEDEP}] )
	globus? ( <=dev-python/pyyaml-6.0.2[${PYTHON_USEDEP}] )
	globus? ( dev-python/globus-sdk[${PYTHON_USEDEP}] )
	saml? ( <=dev-python/python3-saml-1.16.0[${PYTHON_USEDEP}] )
	dev? ( dev-python/pytest[${PYTHON_USEDEP}] )
	dev? ( dev-python/pytest-xdist[${PYTHON_USEDEP}] )
	dev? ( dev-python/pytest-cov[${PYTHON_USEDEP}] )
	dev? ( dev-python/pyflakes[${PYTHON_USEDEP}] )
	dev? ( dev-python/flake8[${PYTHON_USEDEP}] )
	dev? ( dev-python/pylint[${PYTHON_USEDEP}] )
	dev? ( dev-python/isort[${PYTHON_USEDEP}] )
	dev? ( dev-python/xmltodict[${PYTHON_USEDEP}] )
	dev? ( dev-python/pytz[${PYTHON_USEDEP}] )
	dev? ( dev-python/pycodestyle[${PYTHON_USEDEP}] )
	dev? ( dev-python/pydoc-markdown[${PYTHON_USEDEP}] )
	dev? ( dev-python/docspec-python[${PYTHON_USEDEP}] )
	dev? ( dev-python/sh[${PYTHON_USEDEP}] )
	dev? ( dev-python/pyyaml[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
