# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="1.19.1.post10"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="MicroPython stubs"

HOMEPAGE="https://github.com/josverl/micropython-stubs#micropython-stubs"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/8b/3e/899c95b03e4fb88b2ee2ff8482a3c9a5b80588cea2ab477c89ce25a9c0bb/${REALNAME//-/_}-${REALVERSION}.tar.gz"
SOURCEFILE="_}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/micropython-stdlib-stubs[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
