# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="django-ckeditor-5"
LITERALNAME="django-ckeditor-5"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="CKEditor 5 for Django."

HOMEPAGE="https://pypi.org/project/django-ckeditor-5/"
LICENSE="BSD"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME//-/_}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME//-/_}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="dev"
DEPENDENCIES=">=dev-python/django-2.2[${PYTHON_USEDEP}]
	dev-python/pillow[${PYTHON_USEDEP}]
	dev? ( ~dev-python/bandit-1.8.2[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/black-25.1.0[${PYTHON_USEDEP}] )
	dev? ( dev-python/codespell[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/coverage-7.6.10[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/mypy-1.15.0[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/mypy-extensions-1.0.0[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/pytest-8.3.4[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/pytest-cov-6.0.0[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/pytest-django-4.9.0[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/pytest-mock-3.14.0[${PYTHON_USEDEP}] )
	dev? ( dev-python/safety[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/types-setuptools-75.8.0.20250110[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/typing-extensions-4.12.2[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
