# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="A Python API for the Porn Site Eporner.com"

HOMEPAGE="https://github.com/EchterAlsFake/EPorner_API"
LICENSE="LGPL-3"
SRC_URI="https://files.pythonhosted.org/packages/3b/81/13236e772d9f68d54b3b2b36acf41f06ba656dc88a6c98e345d3376b3436/eporner_api-${REALVERSION}.tar.gz"
SOURCEFILE="eporner_api-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/bs4[${PYTHON_USEDEP}]
	dev-python/eaf-base-api[${PYTHON_USEDEP}]
	dev-python/lxml[${PYTHON_USEDEP}]
	dev-python/h2[${PYTHON_USEDEP}]
	dev-python/Brotli[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
