# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=wheel

inherit python-r1 gs-pypi

DESCRIPTION="Simulate Functional Mock-up Units (FMUs) in Python [wheel]"

HOMEPAGE="https://github.com/CATIA-Systems/FMPy"
LICENSE="Standard 2-clause BSD"
SRC_URI="https://files.pythonhosted.org/packages/py3/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}-py3-none-any.whl"
SOURCEFILE="${REALNAME}-${REALVERSION}-py3-none-any.whl"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="complete examples gui notebook plot webapp"
DEPENDENCIES="dev-python/attrs[${PYTHON_USEDEP}]
	dev-python/Jinja2[${PYTHON_USEDEP}]
	dev-python/lark[${PYTHON_USEDEP}]
	dev-python/lxml[${PYTHON_USEDEP}]
	dev-python/msgpack[${PYTHON_USEDEP}]
	dev-python/numpy[${PYTHON_USEDEP}]
	dev-python/pytz[${PYTHON_USEDEP}]
	complete? ( dev-python/PyQt5[${PYTHON_USEDEP}] )
	complete? ( dev-python/PyQtWebEngine[${PYTHON_USEDEP}] )
	complete? ( dev-python/dash-bootstrap-components[${PYTHON_USEDEP}] )
	complete? ( dev-python/dask[${PYTHON_USEDEP}] )
	complete? ( dev-python/kaleido[${PYTHON_USEDEP}] )
	complete? ( dev-python/matplotlib[${PYTHON_USEDEP}] )
	complete? ( dev-python/notebook[${PYTHON_USEDEP}] )
	complete? ( dev-python/plotly[${PYTHON_USEDEP}] )
	complete? ( dev-python/pyqtgraph[${PYTHON_USEDEP}] )
	complete? ( dev-python/requests[${PYTHON_USEDEP}] )
	complete? ( dev-python/scipy[${PYTHON_USEDEP}] )
	examples? ( dev-python/dask[${PYTHON_USEDEP}] )
	examples? ( dev-python/requests[${PYTHON_USEDEP}] )
	gui? ( dev-python/PyQt5[${PYTHON_USEDEP}] )
	gui? ( dev-python/pyqtgraph[${PYTHON_USEDEP}] )
	gui? ( dev-python/PyQtWebEngine[${PYTHON_USEDEP}] )
	notebook? ( dev-python/kaleido[${PYTHON_USEDEP}] )
	notebook? ( dev-python/notebook[${PYTHON_USEDEP}] )
	notebook? ( dev-python/plotly[${PYTHON_USEDEP}] )
	plot? ( dev-python/matplotlib[${PYTHON_USEDEP}] )
	plot? ( dev-python/scipy[${PYTHON_USEDEP}] )
	webapp? ( dev-python/dash-bootstrap-components[${PYTHON_USEDEP}] )
	virtual/allow-pypi-wheels"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
