# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="A Scythe for harvesting OAI-PMH repositories."

HOMEPAGE=""
LICENSE="BSD"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME//-/_}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME//-/_}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="dev docs test"
DEPENDENCIES=">=dev-python/httpx-0.25[${PYTHON_USEDEP}]
	>=dev-python/lxml-5.1[${PYTHON_USEDEP}]
	dev? ( dev-python/pre-commit[${PYTHON_USEDEP}] )
	docs? ( dev-python/mkdocs-include-markdown-plugin[${PYTHON_USEDEP}] )
	docs? ( ~dev-python/mkdocs-material-9.5[${PYTHON_USEDEP}] )
	docs? ( ~dev-python/mkdocstrings-0.24[${PYTHON_USEDEP}] )
	docs? ( ~dev-python/mkdocs-1.5[${PYTHON_USEDEP}] )
	test? ( ~dev-python/pytest-cov-5.0[${PYTHON_USEDEP}] )
	test? ( ~dev-python/pytest-mock-3.12[${PYTHON_USEDEP}] )
	test? ( dev-python/pytest-randomly[${PYTHON_USEDEP}] )
	test? ( ~dev-python/pytest-recording-0.13[${PYTHON_USEDEP}] )
	test? ( ~dev-python/pytest-xdist-3.5[${PYTHON_USEDEP}] )
	test? ( ~dev-python/pytest-8.0[${PYTHON_USEDEP}] )
	test? ( ~dev-python/respx-0.20[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
