# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Education Warehouse maintenance tools"

HOMEPAGE=""
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="b2 bundle bundler dev files locust multipass pip pip-compile plugins restic server-plugins server-provisioning sshfs sshkey uptime whitelabel"
DEPENDENCIES="dev-python/anyio[${PYTHON_USEDEP}]
	dev-python/click[${PYTHON_USEDEP}]
	dev-python/diceware[${PYTHON_USEDEP}]
	dev-python/fabric[${PYTHON_USEDEP}]
	dev-python/humanize[${PYTHON_USEDEP}]
	dev-python/invoke[${PYTHON_USEDEP}]
	dev-python/more-itertools[${PYTHON_USEDEP}]
	dev-python/packaging[${PYTHON_USEDEP}]
	dev-python/plumbum[${PYTHON_USEDEP}]
	dev-python/python-dateutil[${PYTHON_USEDEP}]
	dev-python/pyyaml[${PYTHON_USEDEP}]
	dev-python/rapidfuzz[${PYTHON_USEDEP}]
	dev-python/requests[${PYTHON_USEDEP}]
	dev-python/ruff[${PYTHON_USEDEP}]
	dev-python/tabulate[${PYTHON_USEDEP}]
	dev-python/termcolor[${PYTHON_USEDEP}]
	dev-python/threadful[${PYTHON_USEDEP}]
	dev-python/tomlkit[${PYTHON_USEDEP}]
	dev-python/tqdm[${PYTHON_USEDEP}]
	dev-python/typing-extensions[${PYTHON_USEDEP}]
	dev-python/uv[${PYTHON_USEDEP}]
	dev-python/yayarl[${PYTHON_USEDEP}]
	b2? ( dev-python/edwh-b2-plugin[${PYTHON_USEDEP}] )
	bundle? ( dev-python/edwh-bundler-plugin[${PYTHON_USEDEP}] )
	bundler? ( dev-python/edwh-bundler-plugin[${PYTHON_USEDEP}] )
	dev? ( dev-python/hatch[${PYTHON_USEDEP}] )
	dev? ( dev-python/python-semantic-release[${PYTHON_USEDEP}] )
	dev? ( dev-python/types-python-dateutil[${PYTHON_USEDEP}] )
	dev? ( dev-python/types-redis[${PYTHON_USEDEP}] )
	dev? ( dev-python/types-requests[${PYTHON_USEDEP}] )
	dev? ( dev-python/types-tabulate[${PYTHON_USEDEP}] )
	files? ( dev-python/edwh-files-plugin[${PYTHON_USEDEP}] )
	locust? ( dev-python/edwh-locust-plugin[${PYTHON_USEDEP}] )
	multipass? ( dev-python/edwh-multipass-plugin[${PYTHON_USEDEP}] )
	pip? ( dev-python/edwh-pipcompile-plugin[${PYTHON_USEDEP}] )
	pip-compile? ( dev-python/edwh-pipcompile-plugin[${PYTHON_USEDEP}] )
	plugins? ( dev-python/edwh-b2-plugin[${PYTHON_USEDEP}] )
	plugins? ( dev-python/edwh-bundler-plugin[${PYTHON_USEDEP}] )
	plugins? ( dev-python/edwh-demo-plugin[${PYTHON_USEDEP}] )
	plugins? ( dev-python/edwh-files-plugin[${PYTHON_USEDEP}] )
	plugins? ( dev-python/edwh-locust-plugin[${PYTHON_USEDEP}] )
	plugins? ( dev-python/edwh-multipass-plugin[${PYTHON_USEDEP}] )
	plugins? ( dev-python/edwh-pipcompile-plugin[${PYTHON_USEDEP}] )
	plugins? ( dev-python/edwh-restic-plugin[${PYTHON_USEDEP}] )
	plugins? ( dev-python/edwh-server-provisioning-plugin[${PYTHON_USEDEP}] )
	plugins? ( dev-python/edwh-sshfs-plugin[${PYTHON_USEDEP}] )
	plugins? ( dev-python/edwh-sshkey-plugin[${PYTHON_USEDEP}] )
	plugins? ( dev-python/edwh-uptime-plugin[${PYTHON_USEDEP}] )
	plugins? ( dev-python/edwh-whitelabel-plugin[${PYTHON_USEDEP}] )
	restic? ( dev-python/edwh-restic-plugin[${PYTHON_USEDEP}] )
	server-plugins? ( dev-python/edwh-b2-plugin[${PYTHON_USEDEP}] )
	server-plugins? ( dev-python/edwh-bundler-plugin[${PYTHON_USEDEP}] )
	server-plugins? ( dev-python/edwh-files-plugin[${PYTHON_USEDEP}] )
	server-plugins? ( dev-python/edwh-pipcompile-plugin[${PYTHON_USEDEP}] )
	server-plugins? ( dev-python/edwh-restic-plugin[${PYTHON_USEDEP}] )
	server-plugins? ( dev-python/edwh-uptime-plugin[${PYTHON_USEDEP}] )
	server-provisioning? ( dev-python/edwh-server-provisioning-plugin[${PYTHON_USEDEP}] )
	sshfs? ( dev-python/edwh-sshfs-plugin[${PYTHON_USEDEP}] )
	sshkey? ( dev-python/edwh-sshkey-plugin[${PYTHON_USEDEP}] )
	uptime? ( dev-python/edwh-uptime-plugin[${PYTHON_USEDEP}] )
	whitelabel? ( dev-python/edwh-whitelabel-plugin[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
