# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Hist classes and utilities"

HOMEPAGE="https://github.com/scikit-hep/hist"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="dask dev docs fit mpl plot test"
DEPENDENCIES="dev-python/boost-histogram[${PYTHON_USEDEP}]
	dev-python/histoprint[${PYTHON_USEDEP}]
	>=dev-python/numpy-1.14.5[${PYTHON_USEDEP}]
	>=dev-python/numpy-1.26.0[${PYTHON_USEDEP}]
	>=dev-python/typing-extensions-4.0[${PYTHON_USEDEP}]
	dask? ( dev-python/dask-histogram[${PYTHON_USEDEP}] )
	dask? ( >=dev-python/dask-2022.0[${PYTHON_USEDEP}] )
	dev? ( dev-python/dask-histogram[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/dask-2022.0[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/iminuit-2.0[${PYTHON_USEDEP}] )
	dev? ( dev-python/ipykernel[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/matplotlib-3.0[${PYTHON_USEDEP}] )
	dev? ( dev-python/mplhep[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/pytest-mpl-0.12[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/pytest-6.0[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/scipy-1.4[${PYTHON_USEDEP}] )
	docs? ( dev-python/dask-histogram[${PYTHON_USEDEP}] )
	docs? ( >=dev-python/dask-2022.0[${PYTHON_USEDEP}] )
	docs? ( >=dev-python/graphviz-0.20.1[${PYTHON_USEDEP}] )
	docs? ( >=dev-python/iminuit-2.0[${PYTHON_USEDEP}] )
	docs? ( dev-python/ipykernel[${PYTHON_USEDEP}] )
	docs? ( dev-python/ipython[${PYTHON_USEDEP}] )
	docs? ( dev-python/ipython-genutils[${PYTHON_USEDEP}] )
	docs? ( >=dev-python/matplotlib-3.0[${PYTHON_USEDEP}] )
	docs? ( dev-python/mplhep[${PYTHON_USEDEP}] )
	docs? ( >=dev-python/myst-parser-0.14[${PYTHON_USEDEP}] )
	docs? ( dev-python/nbsphinx[${PYTHON_USEDEP}] )
	docs? ( dev-python/pillow[${PYTHON_USEDEP}] )
	docs? ( >=dev-python/pytest-mpl-0.12[${PYTHON_USEDEP}] )
	docs? ( >=dev-python/pytest-6.0[${PYTHON_USEDEP}] )
	docs? ( >=dev-python/scipy-1.4[${PYTHON_USEDEP}] )
	docs? ( dev-python/sphinx-book-theme[${PYTHON_USEDEP}] )
	docs? ( dev-python/sphinx-copybutton[${PYTHON_USEDEP}] )
	docs? ( >=dev-python/sphinx-3.0.0[${PYTHON_USEDEP}] )
	docs? ( dev-python/sphinxcontrib-programoutput[${PYTHON_USEDEP}] )
	docs? ( >=dev-python/uncertainties-3.0[${PYTHON_USEDEP}] )
	fit? ( >=dev-python/iminuit-2.0[${PYTHON_USEDEP}] )
	fit? ( >=dev-python/scipy-1.4[${PYTHON_USEDEP}] )
	mpl? ( >=dev-python/matplotlib-3.0[${PYTHON_USEDEP}] )
	mpl? ( dev-python/mplhep[${PYTHON_USEDEP}] )
	plot? ( >=dev-python/matplotlib-3.0[${PYTHON_USEDEP}] )
	plot? ( dev-python/mplhep[${PYTHON_USEDEP}] )
	test? ( dev-python/dask-histogram[${PYTHON_USEDEP}] )
	test? ( >=dev-python/dask-2022.0[${PYTHON_USEDEP}] )
	test? ( >=dev-python/pytest-mpl-0.12[${PYTHON_USEDEP}] )
	test? ( >=dev-python/pytest-6.0[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
