# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Lightweight data-centric framework for working with scientific data"

HOMEPAGE="https://github.com/SINTEF/dlite"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/be/de/97d79ca5eed27ea5b8f1f46fc70f9e7e2e34bdff8b9efcabe46507c0133c/dlite_python-${REALVERSION}.tar.gz"
SOURCEFILE="dlite_python-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="<dev-python/numpy-2.1.3[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
