# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Certego SaaS"

HOMEPAGE="https://github.com/certego/certego-saas"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME//-/_}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME//-/_}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="dev"
DEPENDENCIES=">=dev-python/django-2.2.0[${PYTHON_USEDEP}]
	>=dev-python/django-filter-21.1[${PYTHON_USEDEP}]
	dev-python/django-cache-memoize[${PYTHON_USEDEP}]
	dev-python/django-user-agents[${PYTHON_USEDEP}]
	>=dev-python/djangorestframework-3.12.0[${PYTHON_USEDEP}]
	dev-python/drf-spectacular[${PYTHON_USEDEP}]
	dev-python/drf-flex-fields[${PYTHON_USEDEP}]
	dev-python/djangorestframework-filters[${PYTHON_USEDEP}]
	dev-python/django-email-utils[${PYTHON_USEDEP}]
	dev-python/django-rest-durin[${PYTHON_USEDEP}]
	dev-python/drf-recaptcha[${PYTHON_USEDEP}]
	dev-python/slack-sdk[${PYTHON_USEDEP}]
	>=dev-python/stripe-2.61.0[${PYTHON_USEDEP}]
	dev-python/python-twitter[${PYTHON_USEDEP}]
	~dev-python/markdown-3.3.6[${PYTHON_USEDEP}]
	>=dev-python/elasticsearch-6.0.0[${PYTHON_USEDEP}]
	dev? ( >=dev-python/django-2.2.0[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/django-filter-21.1[${PYTHON_USEDEP}] )
	dev? ( dev-python/django-cache-memoize[${PYTHON_USEDEP}] )
	dev? ( dev-python/django-user-agents[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/djangorestframework-3.12.0[${PYTHON_USEDEP}] )
	dev? ( dev-python/drf-spectacular[${PYTHON_USEDEP}] )
	dev? ( dev-python/drf-flex-fields[${PYTHON_USEDEP}] )
	dev? ( dev-python/djangorestframework-filters[${PYTHON_USEDEP}] )
	dev? ( dev-python/django-email-utils[${PYTHON_USEDEP}] )
	dev? ( dev-python/django-rest-durin[${PYTHON_USEDEP}] )
	dev? ( dev-python/drf-recaptcha[${PYTHON_USEDEP}] )
	dev? ( dev-python/slack-sdk[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/stripe-2.61.0[${PYTHON_USEDEP}] )
	dev? ( dev-python/python-twitter[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/markdown-3.3.6[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/elasticsearch-6.0.0[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/flake8-4.0.1[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/black-22.3.0[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/isort-5.10.1[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/pylint-2.12.2[${PYTHON_USEDEP}] )
	dev? ( dev-python/pylint-django[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/mypy-0.910[${PYTHON_USEDEP}] )
	dev? ( dev-python/django-stubs[${PYTHON_USEDEP}] )
	dev? ( dev-python/djangorestframework-stubs[${PYTHON_USEDEP}] )
	dev? ( dev-python/types-Markdown[${PYTHON_USEDEP}] )
	dev? ( ~dev-python/coverage-6.2[${PYTHON_USEDEP}] )
	dev? ( dev-python/tox[${PYTHON_USEDEP}] )
	dev? ( dev-python/tox-gh-actions[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
