# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="0.0.1b23"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="A WebDAV server for Django."

HOMEPAGE="https://github.com/meteozond/djangodav"
LICENSE="UNKNOWN"
SRC_URI="https://files.pythonhosted.org/packages/47/ca/ca9b962f64ad15bfe514b0781075ef89e02e753668bd5e7891a3b22b6031/DjangoDav-${REALVERSION}.tar.gz"
SOURCEFILE="DjangoDav-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=""
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
