# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="endi-base"
REALVERSION="6.4.4"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="endi_base"

HOMEPAGE="https://framagit.org/endi/endi_base"
LICENSE="GPL-3"
SRC_URI="https://files.pythonhosted.org/packages/68/af/0e71acc5582ea760e62eb88f69a26c7ed65f48d4693c3ea3b9ec178d9cce/endi_base-${REALVERSION}.tar.gz"
SOURCEFILE="endi_base-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="testing"
DEPENDENCIES="dev-python/colander[${PYTHON_USEDEP}]
	dev-python/pyramid[${PYTHON_USEDEP}]
	dev-python/unidecode[${PYTHON_USEDEP}]
	dev-python/SQLAlchemy[${PYTHON_USEDEP}]
	dev-python/zope-sqlalchemy[${PYTHON_USEDEP}]
	dev-python/simplejson[${PYTHON_USEDEP}]
	dev-python/pyramid-mailer[${PYTHON_USEDEP}]
	testing? ( dev-python/WebTest[${PYTHON_USEDEP}] )
	testing? ( dev-python/pytest[${PYTHON_USEDEP}] )
	testing? ( dev-python/pytest-cov[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
