# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="diamond-miner"
REALVERSION="1.0.3"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="High-speed, Internet-scale, load-balanced paths discovery."

HOMEPAGE="https://github.com/dioptra-io/diamond-miner"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/15/fc/34b594855f28d6710bda1f9ba87b646b3530cc427df1b1bf95e7679d0e14/diamond_miner-${REALVERSION}.tar.gz"
SOURCEFILE="diamond_miner-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/pych-client[${PYTHON_USEDEP}]
	dev-python/pygfc[${PYTHON_USEDEP}]
	dev-python/zstandard[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
