# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Container class to represent and operate over genomic regions and annotations."

HOMEPAGE="https://github.com/BiocPy/GenomicRanges"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/ba/f2/4dc6a30a1592b40fc260efc65347be089323d9a7195d2d915e1aba37af4b/genomicranges-${REALVERSION}.tar.gz"
SOURCEFILE="genomicranges-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="optional testing"
DEPENDENCIES="dev-python/BiocFrame[${PYTHON_USEDEP}]
	dev-python/IRanges[${PYTHON_USEDEP}]
	dev-python/biocutils[${PYTHON_USEDEP}]
	dev-python/numpy[${PYTHON_USEDEP}]
	optional? ( dev-python/joblib[${PYTHON_USEDEP}] )
	optional? ( dev-python/pandas[${PYTHON_USEDEP}] )
	optional? ( dev-python/polars[${PYTHON_USEDEP}] )
	optional? ( dev-python/matplotlib[${PYTHON_USEDEP}] )
	optional? ( dev-python/biobear[${PYTHON_USEDEP}] )
	testing? ( dev-python/setuptools[${PYTHON_USEDEP}] )
	testing? ( dev-python/pytest[${PYTHON_USEDEP}] )
	testing? ( dev-python/pytest-cov[${PYTHON_USEDEP}] )
	testing? ( dev-python/pandas[${PYTHON_USEDEP}] )
	testing? ( dev-python/polars[${PYTHON_USEDEP}] )
	testing? ( dev-python/matplotlib[${PYTHON_USEDEP}] )
	testing? ( dev-python/joblib[${PYTHON_USEDEP}] )
	testing? ( dev-python/rich[${PYTHON_USEDEP}] )
	testing? ( dev-python/seaborn[${PYTHON_USEDEP}] )
	testing? ( dev-python/biobear[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
