# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="3.0b2"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="A server for file conversions with Libre Office"

HOMEPAGE="https://github.com/unoconv/unoserver"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="devenv"
DEPENDENCIES="devenv? ( dev-python/pytest[${PYTHON_USEDEP}] )
	devenv? ( dev-python/pytest-cov[${PYTHON_USEDEP}] )
	devenv? ( dev-python/black[${PYTHON_USEDEP}] )
	devenv? ( dev-python/flake8[${PYTHON_USEDEP}] )
	devenv? ( dev-python/pyroma[${PYTHON_USEDEP}] )
	devenv? ( dev-python/check-manifest[${PYTHON_USEDEP}] )
	devenv? ( dev-python/zest-releaser[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
