# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=wheel

inherit python-r1 gs-pypi

DESCRIPTION="More Threads! Simpler and faster threading. [wheel]"

HOMEPAGE="https://github.com/klahnakoski/mo-threads"
LICENSE="MPL 2.0"
SRC_URI="https://files.pythonhosted.org/packages/py2.py3/${REALNAME::1}/${REALNAME}/${REALNAME//-/_}-${REALVERSION}-py2.py3-none-any.whl"
SOURCEFILE="${REALNAME//-/_}-${REALVERSION}-py2.py3-none-any.whl"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="+bin-wheel tests"
DEPENDENCIES="dev-python/mo-dots[${PYTHON_USEDEP}]
	dev-python/mo-future[${PYTHON_USEDEP}]
	dev-python/mo-logs[${PYTHON_USEDEP}]
	dev-python/mo-math[${PYTHON_USEDEP}]
	dev-python/mo-times[${PYTHON_USEDEP}]
	tests? ( dev-python/mo-testing[${PYTHON_USEDEP}] )
	tests? ( dev-python/jx-python[${PYTHON_USEDEP}] )
	tests? ( dev-python/psutil[${PYTHON_USEDEP}] )
	tests? ( dev-python/objgraph[${PYTHON_USEDEP}] )
	tests? ( dev-python/mo-files[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
