# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12} )
DISTUTILS_USE_PEP517=wheel

inherit python-r1 gs-pypi

DESCRIPTION="Typhoon Testing Utilities [wheel]"

HOMEPAGE=""
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/96/fa/f6848d835de6c7597955ca82c4f58252ba179e99c9e8ac8fc7634933b9e6/typhoontest-${REALVERSION}-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl"
SOURCEFILE="typhoontest-${REALVERSION}-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/PeakUtils[${PYTHON_USEDEP}]
	dev-python/Typhoon-HIL-API[${PYTHON_USEDEP}]
	~dev-python/numpy-2.2.3[${PYTHON_USEDEP}]
	~dev-python/scipy-1.15.2[${PYTHON_USEDEP}]
	>=dev-python/pytest-5.0[${PYTHON_USEDEP}]
	dev-python/allure-pytest[${PYTHON_USEDEP}]
	~dev-python/pandas-2.2.3[${PYTHON_USEDEP}]
	~dev-python/matplotlib-3.10.0[${PYTHON_USEDEP}]
	dev-python/wrapt[${PYTHON_USEDEP}]
	dev-python/asammdf[${PYTHON_USEDEP}]
	dev-python/npTDMS[${PYTHON_USEDEP}]
	dev-python/pytest-assume[${PYTHON_USEDEP}]
	dev-python/bokeh[${PYTHON_USEDEP}]
	dev-python/psutil[${PYTHON_USEDEP}]
	~dev-python/lz4-4.4.3[${PYTHON_USEDEP}]
	~dev-python/svglib-1.5.1[${PYTHON_USEDEP}]
	~dev-python/reportlab-4.3.1[${PYTHON_USEDEP}]
	dev-python/xhtml2pdf[${PYTHON_USEDEP}]
	dev-python/comtrade[${PYTHON_USEDEP}]
	dev-python/html2image[${PYTHON_USEDEP}]
	dev-python/ldfparser[${PYTHON_USEDEP}]
	dev-python/xlrd[${PYTHON_USEDEP}]
	dev-python/xlwt[${PYTHON_USEDEP}]
	dev-python/xlsxwriter[${PYTHON_USEDEP}]
	~dev-python/jinja2-3.1.5[${PYTHON_USEDEP}]
	~dev-python/tables-3.10.2[${PYTHON_USEDEP}]
	virtual/allow-pypi-wheels"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
