# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="fluxrpc"
REALVERSION="0.11.0"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python3_11 )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="\"A sercure RPC provider for Flux\""

HOMEPAGE=""
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/source/f/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="gevent httpclient msgpack rabbitmq socket websocket wsgi zmq"
DEPENDENCIES="dev-python/six[${PYTHON_USEDEP}]
	socket? ( dev-python/pymongo[${PYTHON_USEDEP}] )
	gevent? ( dev-python/gevent[${PYTHON_USEDEP}] )
	httpclient? ( dev-python/gevent-websocket[${PYTHON_USEDEP}] )
	websocket? ( dev-python/gevent-websocket[${PYTHON_USEDEP}] )
	msgpack? ( dev-python/msgpack[${PYTHON_USEDEP}] )
	rabbitmq? ( dev-python/pika[${PYTHON_USEDEP}] )
	zmq? ( dev-python/pyzmq[${PYTHON_USEDEP}] )
	socket? ( dev-python/pycryptodomex[${PYTHON_USEDEP}] )
	socket? ( dev-python/python-bitcoinlib[${PYTHON_USEDEP}] )
	httpclient? ( dev-python/requests[${PYTHON_USEDEP}] )
	wsgi? ( dev-python/werkzeug[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
