# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="VPP Configuration Utility"

HOMEPAGE="https://wiki.fd.io/view/VPP"
LICENSE="Apache-2.0"
SRC_URI="https://files.pythonhosted.org/packages/d4/cb/dd2c51c127ed6c1657d9d8ccc00e3ee7c731b0ce548c667a4773832edac3/vpp_config-${REALVERSION}.tar.gz"
SOURCEFILE="vpp_config-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/distro[${PYTHON_USEDEP}]
	dev-python/pyyaml[${PYTHON_USEDEP}]
	dev-python/requests[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
