# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="A lightweight python toolkit for gluing together restartable, robust command line pipelines"

HOMEPAGE="https://github.com/databio/pypiper/"
LICENSE="BSD2"
SRC_URI="https://files.pythonhosted.org/packages/source/p/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="all dev ngstk plot"
DEPENDENCIES="dev-python/attmap[${PYTHON_USEDEP}]
	dev-python/logmuse[${PYTHON_USEDEP}]
	dev-python/psutil[${PYTHON_USEDEP}]
	dev-python/pandas[${PYTHON_USEDEP}]
	dev-python/ubiquerg[${PYTHON_USEDEP}]
	dev-python/yacman[${PYTHON_USEDEP}]
	dev-python/pipestat[${PYTHON_USEDEP}]
	all? ( dev-python/seaborn[${PYTHON_USEDEP}] )
	all? ( dev-python/scipy[${PYTHON_USEDEP}] )
	all? ( dev-python/matplotlib[${PYTHON_USEDEP}] )
	all? ( dev-python/pysam[${PYTHON_USEDEP}] )
	all? ( dev-python/numpy[${PYTHON_USEDEP}] )
	all? ( dev-python/pandas[${PYTHON_USEDEP}] )
	all? ( dev-python/pipestat[${PYTHON_USEDEP}] )
	all? ( dev-python/yacman[${PYTHON_USEDEP}] )
	dev? ( dev-python/seaborn[${PYTHON_USEDEP}] )
	dev? ( dev-python/mock[${PYTHON_USEDEP}] )
	dev? ( dev-python/pytest[${PYTHON_USEDEP}] )
	dev? ( dev-python/pytest-remotedata[${PYTHON_USEDEP}] )
	dev? ( dev-python/veracitools[${PYTHON_USEDEP}] )
	dev? ( dev-python/pytest-cov[${PYTHON_USEDEP}] )
	dev? ( dev-python/scipy[${PYTHON_USEDEP}] )
	dev? ( dev-python/matplotlib[${PYTHON_USEDEP}] )
	dev? ( dev-python/coveralls[${PYTHON_USEDEP}] )
	dev? ( dev-python/hypothesis[${PYTHON_USEDEP}] )
	dev? ( dev-python/pysam[${PYTHON_USEDEP}] )
	dev? ( dev-python/numpy[${PYTHON_USEDEP}] )
	dev? ( dev-python/pandas[${PYTHON_USEDEP}] )
	dev? ( dev-python/pipestat[${PYTHON_USEDEP}] )
	dev? ( dev-python/yacman[${PYTHON_USEDEP}] )
	ngstk? ( dev-python/numpy[${PYTHON_USEDEP}] )
	ngstk? ( dev-python/pandas[${PYTHON_USEDEP}] )
	ngstk? ( dev-python/pysam[${PYTHON_USEDEP}] )
	ngstk? ( dev-python/yacman[${PYTHON_USEDEP}] )
	ngstk? ( dev-python/pipestat[${PYTHON_USEDEP}] )
	plot? ( dev-python/matplotlib[${PYTHON_USEDEP}] )
	plot? ( dev-python/scipy[${PYTHON_USEDEP}] )
	plot? ( dev-python/seaborn[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
