# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=wheel

inherit python-r1 gs-pypi

DESCRIPTION="A Python module for accessing the Kaltura API. [wheel]"

HOMEPAGE="https://github.com/kaltura/KalturaGeneratedAPIClientsPython"
LICENSE="AGPL-3+"
SRC_URI="https://files.pythonhosted.org/packages/26/95/a233b8d9a0e31b9bf5637dcf380d3e8c32d5ce1bf6840044a23eb3c8af3f/kalturaapiclient-${REALVERSION}-py2.py3-none-any.whl"
SOURCEFILE="kalturaapiclient-${REALVERSION}-py2.py3-none-any.whl"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=">=dev-python/requests-2.4.2[${PYTHON_USEDEP}]
	dev-python/requests-toolbelt[${PYTHON_USEDEP}]
	dev-python/six[${PYTHON_USEDEP}]
	virtual/allow-pypi-wheels"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
