# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="AI-assisted debugging. Uses AI to answer 'why'."

HOMEPAGE="https://github.com/plasma-umass/ChatDBG"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/de/37/965d03b7a83edd33a4b85a3f0e8b906124c85b0f7e158b3a4f0e14db7d34/chatdbg-${REALVERSION}.tar.gz"
SOURCEFILE="chatdbg-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/ansicolors[${PYTHON_USEDEP}]
	>=dev-python/ipdb-0.13.13[${PYTHON_USEDEP}]
	dev-python/ipyflow[${PYTHON_USEDEP}]
	>=dev-python/ipython-8.18.1[${PYTHON_USEDEP}]
	dev-python/litellm[${PYTHON_USEDEP}]
	dev-python/llm-utils[${PYTHON_USEDEP}]
	>=dev-python/numpy-1.26.3[${PYTHON_USEDEP}]
	dev-python/openai[${PYTHON_USEDEP}]
	>=dev-python/pyyaml-6.0.1[${PYTHON_USEDEP}]
	>=dev-python/rich-13.7.0[${PYTHON_USEDEP}]
	>=dev-python/traitlets-5.14.1[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
