# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="This is the custom Python library of @CoderElijah on https://replit.com/."

HOMEPAGE=""
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/61/1e/6abcf66ed2f4eb78bc245e92a689494e9b9b5332fd1ceb8fd2b8a7c9a03f/CoderElijah-${REALVERSION}.tar.gz"
SOURCEFILE="CoderElijah-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/numpy[${PYTHON_USEDEP}]
	dev-python/replit[${PYTHON_USEDEP}]
	dev-python/Flask[${PYTHON_USEDEP}]
	dev-python/urllib3[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
