# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="1.10.3b4"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Great Expectations Plugin for Flytekit"

HOMEPAGE=""
LICENSE="Apache-2.0"
SRC_URI="https://files.pythonhosted.org/packages/de/3a/f257eacd8ea714b694a7d6bccb288e408272c2976fc2897947687d61e3c0/flytekitplugins-great_expectations-${REALVERSION}.tar.gz"
SOURCEFILE="flytekitplugins-great_expectations-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/flytekit[${PYTHON_USEDEP}]
	dev-python/great-expectations[${PYTHON_USEDEP}]
	<dev-python/sqlalchemy-2.0.0[${PYTHON_USEDEP}]
	dev-python/pyspark[${PYTHON_USEDEP}]
	dev-python/flytekitplugins-spark[${PYTHON_USEDEP}]
	dev-python/s3fs[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
