# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Offensive API tester tool automates checks for common API vulnerabilities"

HOMEPAGE=""
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="api"
DEPENDENCIES="<dev-python/aiohttp-4.0.0[${PYTHON_USEDEP}]
	dev-python/aiolimiter[${PYTHON_USEDEP}]
	api? ( dev-python/fastapi[${PYTHON_USEDEP}] )
	<dev-python/openapi-spec-validator-0.8.0[${PYTHON_USEDEP}]
	api? ( <dev-python/python-dotenv-2.0.0[${PYTHON_USEDEP}] )
	<dev-python/pyyaml-7.0[${PYTHON_USEDEP}]
	api? ( <dev-python/redis-6.0.0[${PYTHON_USEDEP}] )
	<dev-python/rich-14.0.0[${PYTHON_USEDEP}]
	api? ( <dev-python/rq-2.0.0[${PYTHON_USEDEP}] )
	<dev-python/setuptools-70.0.0[${PYTHON_USEDEP}]
	api? ( <dev-python/uvicorn-0.24.0[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
