# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Pac-man with ducks"

HOMEPAGE="https://github.com/AbraaoCF/Pato-man"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/df/b7/d811fbc7330c30dabd103d39edc1d4086887bf95fa61c9c55b731a05b9c8/Pato-man-${REALVERSION}.tar.gz"
SOURCEFILE="Pato-man-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/pygame[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
