# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="A fluent design widgets library based on PyQt5"

HOMEPAGE="https://qfluentwidgets.com"
LICENSE="GPL-3"
SRC_URI="https://files.pythonhosted.org/packages/71/e0/56d5a67f97708297a7c044dd4c93d796512fed510d5db6f54ca479bc530e/pyqt_fluent_widgets-${REALVERSION}.tar.gz"
SOURCEFILE="pyqt_fluent_widgets-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="full"
DEPENDENCIES="dev-python/PyQt5[${PYTHON_USEDEP}]
	dev-python/PyQt5-Frameless-Window[${PYTHON_USEDEP}]
	dev-python/darkdetect[${PYTHON_USEDEP}]
	full? ( dev-python/scipy[${PYTHON_USEDEP}] )
	full? ( dev-python/pillow[${PYTHON_USEDEP}] )
	full? ( dev-python/colorthief[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
