# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Lab Equipment Automation Package"

HOMEPAGE="https://kylejeanlewis.github.io/control-lab-ly/"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME//-/_}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME//-/_}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="all ax8 biologic dev docs keithley"
DEPENDENCIES=">=dev-python/matplotlib-3.9[${PYTHON_USEDEP}]
	>=dev-python/numpy-2.0[${PYTHON_USEDEP}]
	dev-python/opencv-python[${PYTHON_USEDEP}]
	>=dev-python/pandas-2.0[${PYTHON_USEDEP}]
	>=dev-python/parse-1.20[${PYTHON_USEDEP}]
	>=dev-python/pyserial-3.5[${PYTHON_USEDEP}]
	>=dev-python/pyyaml-6.0.1[${PYTHON_USEDEP}]
	>=dev-python/scipy-1.14[${PYTHON_USEDEP}]
	dev? ( >=dev-python/pytest-7.4[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/pytest-cov-2.11[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/pytest-rerunfailures-15.0[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/pytest-xdist-3.6[${PYTHON_USEDEP}] )
	dev? ( >=dev-python/tox-3.24[${PYTHON_USEDEP}] )
	docs? ( >=dev-python/mkdocs-1.6.1[${PYTHON_USEDEP}] )
	docs? ( >=dev-python/mkdocs-material-9.6.14[${PYTHON_USEDEP}] )
	docs? ( >=dev-python/mkdocstrings-python-1.16.12[${PYTHON_USEDEP}] )
	docs? ( dev-python/ruff[${PYTHON_USEDEP}] )
	all? ( dev-python/pyModbusTCP[${PYTHON_USEDEP}] )
	all? ( dev-python/easy-biologic[${PYTHON_USEDEP}] )
	all? ( >=dev-python/nest-asyncio-1.6.0[${PYTHON_USEDEP}] )
	all? ( >=dev-python/setuptools-71.0.3[${PYTHON_USEDEP}] )
	all? ( dev-python/PyMeasure[${PYTHON_USEDEP}] )
	ax8? ( dev-python/pyModbusTCP[${PYTHON_USEDEP}] )
	biologic? ( dev-python/easy-biologic[${PYTHON_USEDEP}] )
	biologic? ( >=dev-python/nest-asyncio-1.6.0[${PYTHON_USEDEP}] )
	biologic? ( >=dev-python/setuptools-71.0.3[${PYTHON_USEDEP}] )
	keithley? ( dev-python/PyMeasure[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
