# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Easy-to-use asynchronous TDLib wrapper for Python."

HOMEPAGE="https://github.com/pytdbot/client"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/bc/01/586429da8c0fc73d0362515f1b9d49fa6ebfd3c718390a32b5a2cb8e8042/pytdbot-${REALVERSION}.tar.gz"
SOURCEFILE="pytdbot-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="tdjson"
DEPENDENCIES="dev-python/deepdiff[${PYTHON_USEDEP}]
	dev-python/aio-pika[${PYTHON_USEDEP}]
	tdjson? ( dev-python/tdjson[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
