# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=wheel

inherit python-r1 gs-pypi

DESCRIPTION="Various utilities used for analysis of YANG models. [wheel]"

HOMEPAGE="https://developer.cisco.com/yangsuite"
LICENSE="Cisco End User License Agreement"
SRC_URI="https://files.pythonhosted.org/packages/py3/${REALNAME::1}/${REALNAME}/${REALNAME//-/_}-${REALVERSION}-py3-none-any.whl"
SOURCEFILE="${REALNAME//-/_}-${REALVERSION}-py3-none-any.whl"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/yangsuite[${PYTHON_USEDEP}]
	dev-python/yangsuite-yangtree[${PYTHON_USEDEP}]
	dev-python/yangsuite-filemanager[${PYTHON_USEDEP}]
	dev-python/yangsuite-devices[${PYTHON_USEDEP}]
	dev-python/yangsuite-netconf[${PYTHON_USEDEP}]
	<dev-python/requests-3.0[${PYTHON_USEDEP}]
	<dev-python/docker-5.0.0[${PYTHON_USEDEP}]
	dev-python/pandas[${PYTHON_USEDEP}]
	<dev-python/elasticsearch-8.0.0[${PYTHON_USEDEP}]
	<dev-python/markupsafe-2.1.0[${PYTHON_USEDEP}]
	dev-python/openpyxl[${PYTHON_USEDEP}]
	dev-python/xlsxwriter[${PYTHON_USEDEP}]
	~dev-python/deepdiff-4.0.7[${PYTHON_USEDEP}]
	dev-python/regex[${PYTHON_USEDEP}]
	virtual/allow-pypi-wheels"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
