# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Python Speech Language Sample Analysis"

HOMEPAGE=""
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="dev docs train"
DEPENDENCIES=">=dev-python/pydantic-2.4[${PYTHON_USEDEP}]
	dev-python/nltk[${PYTHON_USEDEP}]
	dev-python/praatio[${PYTHON_USEDEP}]
	dev-python/torch[${PYTHON_USEDEP}]
	dev-python/torchaudio[${PYTHON_USEDEP}]
	dev-python/pydub[${PYTHON_USEDEP}]
	>=dev-python/plotly-5.3.0[${PYTHON_USEDEP}]
	dev-python/transformers[${PYTHON_USEDEP}]
	dev-python/tokenizers[${PYTHON_USEDEP}]
	>=dev-python/pycountry-22.3[${PYTHON_USEDEP}]
	dev-python/stanza[${PYTHON_USEDEP}]
	~dev-python/scipy-1.11[${PYTHON_USEDEP}]
	dev-python/rev-ai[${PYTHON_USEDEP}]
	~dev-python/rich-13.6[${PYTHON_USEDEP}]
	dev-python/omegaconf[${PYTHON_USEDEP}]
	~dev-python/click-8.1[${PYTHON_USEDEP}]
	<dev-python/matplotlib-4.0.0[${PYTHON_USEDEP}]
	dev-python/pyfiglet[${PYTHON_USEDEP}]
	>=dev-python/setuptools-78.1.1[${PYTHON_USEDEP}]
	~dev-python/soundfile-0.12.0[${PYTHON_USEDEP}]
	>=dev-python/rich-click-1.7.0[${PYTHON_USEDEP}]
	dev-python/typing-extensions[${PYTHON_USEDEP}]
	dev-python/num2words[${PYTHON_USEDEP}]
	dev-python/tiktoken[${PYTHON_USEDEP}]
	dev-python/blobfile[${PYTHON_USEDEP}]
	dev-python/sentencepiece[${PYTHON_USEDEP}]
	dev-python/googletrans[${PYTHON_USEDEP}]
	dev-python/openai-whisper[${PYTHON_USEDEP}]
	dev-python/praat-parselmouth[${PYTHON_USEDEP}]
	dev? ( dev-python/pytest[${PYTHON_USEDEP}] )
	train? ( dev-python/accelerate[${PYTHON_USEDEP}] )
	docs? ( dev-python/mkdocs-material[${PYTHON_USEDEP}] )
	docs? ( dev-python/mkdocs-click[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
