# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="The Python Stellar SDK library provides APIs to build transactions and connect to Horizon."

HOMEPAGE="https://github.com/StellarCN/py-stellar-base"
LICENSE="Apache-2.0"
SRC_URI="https://files.pythonhosted.org/packages/f1/d6/9e3ddc30a25f401b2f5ddcf19c4ea4d2dfb9854893239a427a132da9b784/stellar_sdk-${REALVERSION}.tar.gz"
SOURCEFILE="stellar_sdk-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/PyNaCl[${PYTHON_USEDEP}]
	dev-python/aiohttp[${PYTHON_USEDEP}]
	dev-python/aiohttp-sse-client[${PYTHON_USEDEP}]
	dev-python/mnemonic[${PYTHON_USEDEP}]
	dev-python/requests[${PYTHON_USEDEP}]
	dev-python/stellar-base-sseclient[${PYTHON_USEDEP}]
	dev-python/toml[${PYTHON_USEDEP}]
	dev-python/typeguard[${PYTHON_USEDEP}]
	dev-python/urllib3[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
