# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="HTTP Client for Hella's ONYX.CENTER API."

HOMEPAGE="https://github.com/muhlba91/onyx-client"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/65/cd/b71d2335e42a3efc6c22251c4a513dfc63b700c647cedcb29b27a8ad73f1/onyx_client-${REALVERSION}.tar.gz"
SOURCEFILE="onyx_client-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/aiohttp[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
