# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Multi-variable polynomial regression for curve fitting."

HOMEPAGE="https://github.com/Joel-H-dot/MVPR"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/d3/54/8dc6c69cb1841d2cfe774e6522224bdeb1c820db642612ecd59b7be3dd8a/MVPR-${REALVERSION}.tar.gz"
SOURCEFILE="MVPR-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/numpy[${PYTHON_USEDEP}]
	dev-python/sklearn[${PYTHON_USEDEP}]
	dev-python/scipy[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
