# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Planetmint: The Blockchain Database"

HOMEPAGE=""
LICENSE="AGPL-3"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="~dev-python/chardet-3.0.4[${PYTHON_USEDEP}]
	dev-python/base58[${PYTHON_USEDEP}]
	~dev-python/aiohttp-3.9.5[${PYTHON_USEDEP}]
	~dev-python/flask-cors-3.0.10[${PYTHON_USEDEP}]
	dev-python/Flask-RESTful[${PYTHON_USEDEP}]
	~dev-python/flask-2.1.2[${PYTHON_USEDEP}]
	dev-python/gunicorn[${PYTHON_USEDEP}]
	~dev-python/jsonschema-4.16.0[${PYTHON_USEDEP}]
	dev-python/logstats[${PYTHON_USEDEP}]
	>=dev-python/packaging-22.0[${PYTHON_USEDEP}]
	~dev-python/pymongo-3.11.4[${PYTHON_USEDEP}]
	dev-python/tarantool[${PYTHON_USEDEP}]
	dev-python/python-rapidjson[${PYTHON_USEDEP}]
	~dev-python/pyyaml-6.0.2[${PYTHON_USEDEP}]
	~dev-python/requests-2.31.0[${PYTHON_USEDEP}]
	~dev-python/setproctitle-1.2.2[${PYTHON_USEDEP}]
	~dev-python/werkzeug-2.0.3[${PYTHON_USEDEP}]
	~dev-python/nest-asyncio-1.5.5[${PYTHON_USEDEP}]
	~dev-python/protobuf-3.20.2[${PYTHON_USEDEP}]
	dev-python/planetmint-ipld[${PYTHON_USEDEP}]
	>=dev-python/pyasn1-0.4.8[${PYTHON_USEDEP}]
	dev-python/python-decouple[${PYTHON_USEDEP}]
	dev-python/planetmint-transactions[${PYTHON_USEDEP}]
	dev-python/asynctnt[${PYTHON_USEDEP}]
	dev-python/planetmint-abci[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
