# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Image processing blend modes"

HOMEPAGE="https://github.com/flrs/blend_modes"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/b4/00/61401b0ef3a1e58e2ba305292fef3fc043be4eff0162138e67d9b9fc77de/blend_modes-${REALVERSION}.tar.gz"
SOURCEFILE="blend_modes-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=""
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
