# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="htseq-clip"
REALVERSION="2.18.2b0"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="htseq-clip: a toolset for the analysis of eCLIP/iCLIP datasets"

HOMEPAGE="https://github.com/EMBL-Hentze-group/htseq-clip"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/source/h/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/HTSeq[${PYTHON_USEDEP}]
	dev-python/pysam[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
