# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="airflow-provider-anomaly-detection"
REALVERSION="0.0.20"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="An airflow provider for anomaly detection."

HOMEPAGE="https://github.com/andrewm4894/airflow-provider-anomaly-detection"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/23/5c/96a24047a56b0b4588045f814907fe19b0c39a9cf3201475e67d6c7a4344/airflow_provider_anomaly_detection-${REALVERSION}.tar.gz"
SOURCEFILE="airflow_provider_anomaly_detection-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=""
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
