# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="A modular, fast, simple, static website and blog generator"

HOMEPAGE="https://getnikola.com/"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="extras full tests"
DEPENDENCIES=">=dev-python/doit-0.32.0[${PYTHON_USEDEP}]
	>=dev-python/pygments-1.6[${PYTHON_USEDEP}]
	>=dev-python/pillow-2.4.0[${PYTHON_USEDEP}]
	>=dev-python/python-dateutil-2.6.0[${PYTHON_USEDEP}]
	>=dev-python/docutils-0.13[${PYTHON_USEDEP}]
	>=dev-python/mako-1.0.0[${PYTHON_USEDEP}]
	>=dev-python/markdown-3.0.0[${PYTHON_USEDEP}]
	>=dev-python/unidecode-0.4.16[${PYTHON_USEDEP}]
	>=dev-python/lxml-3.3.5[${PYTHON_USEDEP}]
	>=dev-python/PyRSS2Gen-1.1[${PYTHON_USEDEP}]
	>=dev-python/blinker-1.3[${PYTHON_USEDEP}]
	>=dev-python/setuptools-24.2.0[${PYTHON_USEDEP}]
	>=dev-python/natsort-3.5.2[${PYTHON_USEDEP}]
	>=dev-python/requests-2.2.0[${PYTHON_USEDEP}]
	>=dev-python/piexif-1.0.3[${PYTHON_USEDEP}]
	>=dev-python/Babel-2.6.0[${PYTHON_USEDEP}]
	extras? ( dev-python/Jinja2[${PYTHON_USEDEP}] )
	extras? ( dev-python/hsluv[${PYTHON_USEDEP}] )
	extras? ( >=dev-python/pyphen-0.9.1[${PYTHON_USEDEP}] )
	extras? ( >=dev-python/micawber-0.3.0[${PYTHON_USEDEP}] )
	extras? ( >=dev-python/pygal-2.0.0[${PYTHON_USEDEP}] )
	extras? ( >=dev-python/typogrify-2.0.4[${PYTHON_USEDEP}] )
	extras? ( dev-python/phpserialize[${PYTHON_USEDEP}] )
	extras? ( >=dev-python/notebook-4.0.0[${PYTHON_USEDEP}] )
	extras? ( >=dev-python/ipykernel-4.0.0[${PYTHON_USEDEP}] )
	extras? ( >=dev-python/ghp-import-1.0.0[${PYTHON_USEDEP}] )
	extras? ( >=dev-python/aiohttp-3.0.0[${PYTHON_USEDEP}] )
	extras? ( >=dev-python/watchdog-0.8.3[${PYTHON_USEDEP}] )
	extras? ( >=dev-python/ruamel-yaml-0.15[${PYTHON_USEDEP}] )
	extras? ( dev-python/toml[${PYTHON_USEDEP}] )
	extras? ( >=dev-python/html5lib-1.0[${PYTHON_USEDEP}] )
	full? ( dev-python/Jinja2[${PYTHON_USEDEP}] )
	full? ( dev-python/hsluv[${PYTHON_USEDEP}] )
	full? ( >=dev-python/pyphen-0.9.1[${PYTHON_USEDEP}] )
	full? ( >=dev-python/micawber-0.3.0[${PYTHON_USEDEP}] )
	full? ( >=dev-python/pygal-2.0.0[${PYTHON_USEDEP}] )
	full? ( >=dev-python/typogrify-2.0.4[${PYTHON_USEDEP}] )
	full? ( dev-python/phpserialize[${PYTHON_USEDEP}] )
	full? ( >=dev-python/notebook-4.0.0[${PYTHON_USEDEP}] )
	full? ( >=dev-python/ipykernel-4.0.0[${PYTHON_USEDEP}] )
	full? ( >=dev-python/ghp-import-1.0.0[${PYTHON_USEDEP}] )
	full? ( >=dev-python/aiohttp-3.0.0[${PYTHON_USEDEP}] )
	full? ( >=dev-python/watchdog-0.8.3[${PYTHON_USEDEP}] )
	full? ( >=dev-python/ruamel-yaml-0.15[${PYTHON_USEDEP}] )
	full? ( dev-python/toml[${PYTHON_USEDEP}] )
	full? ( >=dev-python/html5lib-1.0[${PYTHON_USEDEP}] )
	tests? ( >=dev-python/coverage-4.5.1[${PYTHON_USEDEP}] )
	tests? ( >=dev-python/pytest-4.1.0[${PYTHON_USEDEP}] )
	tests? ( >=dev-python/pytest-cov-2.6.1[${PYTHON_USEDEP}] )
	tests? ( >=dev-python/feedparser-6.0.10[${PYTHON_USEDEP}] )
	tests? ( >=dev-python/freezegun-0.3.10[${PYTHON_USEDEP}] )
	tests? ( >=dev-python/flake8-3.7.7[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
