# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="elifecleaner"
REALVERSION="0.30.0"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Clean and transform article submission files into a consistent format."

HOMEPAGE="https://github.com/elifesciences/elife-cleaner"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/source/e/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/docmaptools[${PYTHON_USEDEP}]
	dev-python/elifetools[${PYTHON_USEDEP}]
	dev-python/elifearticle[${PYTHON_USEDEP}]
	dev-python/jatsgenerator[${PYTHON_USEDEP}]
	dev-python/PyYAML[${PYTHON_USEDEP}]
	dev-python/wand[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
