# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="P(i/y)thon h(i/y)stograms."

HOMEPAGE=""
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="all astropy dask folium matplotlib pandas plotly polars xarray"
DEPENDENCIES=">=dev-python/numpy-1.25[${PYTHON_USEDEP}]
	dev-python/packaging[${PYTHON_USEDEP}]
	dev-python/typing-extensions[${PYTHON_USEDEP}]
	>=dev-python/hypothesis-6.96.1[${PYTHON_USEDEP}]
	>=dev-python/click-8.1.8[${PYTHON_USEDEP}]
	>=dev-python/narwhals-2.0.1[${PYTHON_USEDEP}]
	>=dev-python/rich-14.1.0[${PYTHON_USEDEP}]
	all? ( dev-python/physt[${PYTHON_USEDEP}] )
	astropy? ( dev-python/astropy[${PYTHON_USEDEP}] )
	dask? ( dev-python/dask[${PYTHON_USEDEP}] )
	folium? ( dev-python/folium[${PYTHON_USEDEP}] )
	matplotlib? ( >=dev-python/matplotlib-3.0[${PYTHON_USEDEP}] )
	pandas? ( >=dev-python/pandas-1.3[${PYTHON_USEDEP}] )
	plotly? ( dev-python/plotly[${PYTHON_USEDEP}] )
	polars? ( dev-python/polars[${PYTHON_USEDEP}] )
	polars? ( dev-python/physt[${PYTHON_USEDEP}] )
	xarray? ( dev-python/xarray[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
