# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Build GUI for your Python program with JavaScript, HTML, and CSS"

HOMEPAGE="https://pywebview.flowrl.com/"
LICENSE="BSD 3-Clause License"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="android cef gtk pyside2 pyside6 qt qt5 qt6 ssl"
DEPENDENCIES="dev-python/pyobjc-core[${PYTHON_USEDEP}]
	dev-python/pyobjc-framework-Cocoa[${PYTHON_USEDEP}]
	dev-python/pyobjc-framework-Quartz[${PYTHON_USEDEP}]
	dev-python/pyobjc-framework-WebKit[${PYTHON_USEDEP}]
	dev-python/pyobjc-framework-Security[${PYTHON_USEDEP}]
	dev-python/QtPy[${PYTHON_USEDEP}]
	dev-python/proxy_tools[${PYTHON_USEDEP}]
	dev-python/bottle[${PYTHON_USEDEP}]
	dev-python/typing-extensions[${PYTHON_USEDEP}]
	cef? ( dev-python/cefpython3[${PYTHON_USEDEP}] )
	gtk? ( ~dev-python/pygobject-3.50.0[${PYTHON_USEDEP}] )
	gtk? ( dev-python/PyGObject-stubs[${PYTHON_USEDEP}] )
	pyside2? ( dev-python/QtPy[${PYTHON_USEDEP}] )
	pyside2? ( dev-python/pyside2[${PYTHON_USEDEP}] )
	pyside6? ( dev-python/QtPy[${PYTHON_USEDEP}] )
	pyside6? ( dev-python/pyside6[${PYTHON_USEDEP}] )
	qt? ( dev-python/QtPy[${PYTHON_USEDEP}] )
	qt? ( dev-python/PyQt6[${PYTHON_USEDEP}] )
	qt? ( dev-python/PyQt6-WebEngine[${PYTHON_USEDEP}] )
	qt5? ( dev-python/QtPy[${PYTHON_USEDEP}] )
	qt5? ( dev-python/PyQt5[${PYTHON_USEDEP}] )
	qt5? ( dev-python/PyQtWebEngine[${PYTHON_USEDEP}] )
	qt6? ( dev-python/QtPy[${PYTHON_USEDEP}] )
	qt6? ( dev-python/PyQt6[${PYTHON_USEDEP}] )
	qt6? ( dev-python/PyQt6-WebEngine[${PYTHON_USEDEP}] )
	android? ( dev-python/Kivy[${PYTHON_USEDEP}] )
	android? ( dev-python/jnius[${PYTHON_USEDEP}] )
	ssl? ( dev-python/cryptography[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
