# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="A lightweight framework for flow-based programming in python."

HOMEPAGE="https://github.com/PaulSchweizer/flowpipe"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/35/a7/9af1b48aebc6ffffb01b9d951f20f57300b85a827933d84549c4465b409d/flowpipe-${REALVERSION}.tar.gz"
SOURCEFILE="flowpipe-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/ascii-canvas[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
