# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="CMS Monitoring utilities"

HOMEPAGE="https://github.com/dmwm/CMSMonitoring"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/96/d0/e5a3da705c05af1a8b0613c0ffb815fb42f39ed37c26067f8ed4912d503e/CMSMonitoring-${REALVERSION}.tar.gz"
SOURCEFILE="CMSMonitoring-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/setuptools[${PYTHON_USEDEP}]
	dev-python/click[${PYTHON_USEDEP}]
	dev-python/stomp-py[${PYTHON_USEDEP}]
	dev-python/jsonschema[${PYTHON_USEDEP}]
	dev-python/nats-py[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
