# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Use Open AI models in xonsh shell."

HOMEPAGE="https://github.com/anki-code/xontrib-openai"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/fc/bd/56413c4ce62b6a6f211201a60ad1d190ce842037dafa192eaab5c8ab3fef/${REALNAME//-/_}-${REALVERSION}.tar.gz"
SOURCEFILE="_}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/openai[${PYTHON_USEDEP}]
	dev-python/xonsh[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
