# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Easy and fast tool written in python 3 to get info about running ngrok tunnel"

HOMEPAGE="https://github.com/HexagonCore/get-ngrok-tunnel-info"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/5e/19/837942075bbb546343d44aa6829f0dafec185684b9f72cef2047931abd53/ngrok_info-${REALVERSION}.tar.gz"
SOURCEFILE="ngrok_info-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/markdown[${PYTHON_USEDEP}]
	dev-python/requests[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
