# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Scientific reports with embedded python computations with reST, LaTeX or markdown"

HOMEPAGE="http://mpastell.com/pweave"
LICENSE="LICENSE.txt"
SRC_URI="https://files.pythonhosted.org/packages/4d/19/1d26e59f8928592062cfd4cd40084285be770b3a4735fff2aa38b97d1aaf/Pweave-${REALVERSION}.tar.gz"
SOURCEFILE="Pweave-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=""
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
