# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="dbt-spark"
REALVERSION="1.4.1"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
REPO_URI="http://pypi.python.org/packages/source/${REALNAME:0:1}/${REALNAME}/"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
DISTUTILS_USE_PEP517=standalone

inherit gs-pypi

DESCRIPTION="The Apache Spark adapter plugin for dbt"

HOMEPAGE="https://github.com/dbt-labs/dbt-spark"
LICENSE=""
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="all odbc pyhive session"
DEPENDENCIES="dev-python/dbt-core[${PYTHON_USEDEP}]
	dev-python/sqlparams[${PYTHON_USEDEP}]
	odbc? ( dev-python/pyodbc[${PYTHON_USEDEP}] )
	pyhive? ( dev-python/PyHive[${PYTHON_USEDEP}] )
	pyhive? ( dev-python/thrift[${PYTHON_USEDEP}] )
	all? ( dev-python/pyodbc[${PYTHON_USEDEP}] )
	all? ( dev-python/PyHive[${PYTHON_USEDEP}] )
	all? ( dev-python/thrift[${PYTHON_USEDEP}] )
	all? ( dev-python/pyspark[${PYTHON_USEDEP}] )
	session? ( dev-python/pyspark[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
