# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION=""

HOMEPAGE="https://github.com/DataShades/ckanext-resource_indexer"
LICENSE="AGPL-3"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME//-/_}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME//-/_}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="all dev pdf test"
DEPENDENCIES="dev-python/ckantoolkit[${PYTHON_USEDEP}]
	dev-python/six[${PYTHON_USEDEP}]
	pdf? ( dev-python/pdftotext[${PYTHON_USEDEP}] )
	all? ( dev-python/pdftotext[${PYTHON_USEDEP}] )
	test? ( dev-python/pytest-ckan[${PYTHON_USEDEP}] )
	test? ( dev-python/pytest-factoryboy[${PYTHON_USEDEP}] )
	dev? ( dev-python/pdftotext[${PYTHON_USEDEP}] )
	dev? ( dev-python/pytest-ckan[${PYTHON_USEDEP}] )
	dev? ( dev-python/pytest-factoryboy[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
