# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Server deployment and configuration management in Python"

HOMEPAGE="http://yaybu.com/"
LICENSE="Apache-2.0"
SRC_URI="https://files.pythonhosted.org/packages/30/38/4d53b06950ea1b8322890e2c3f8507379268fe4e6cb83aa5f4358f87a015/Yaybu-${REALVERSION}.zip"
SOURCEFILE="Yaybu-${REALVERSION}.zip"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=""
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
