# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Module providing logging capabilities."

HOMEPAGE="https://github.com/inveniosoftware/invenio-logging"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/source/${REALNAME::1}/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="all docs sentry sentry-sdk tests"
DEPENDENCIES="dev-python/invenio-celery[${PYTHON_USEDEP}]
	dev-python/invenio-db[${PYTHON_USEDEP}]
	all? ( dev-python/Sphinx[${PYTHON_USEDEP}] )
	all? ( dev-python/flask-login[${PYTHON_USEDEP}] )
	all? ( dev-python/httpretty[${PYTHON_USEDEP}] )
	all? ( dev-python/mock[${PYTHON_USEDEP}] )
	all? ( dev-python/pytest-invenio[${PYTHON_USEDEP}] )
	all? ( dev-python/iniconfig[${PYTHON_USEDEP}] )
	all? ( dev-python/raven[${PYTHON_USEDEP}] )
	all? ( dev-python/sentry-sdk[${PYTHON_USEDEP}] )
	docs? ( dev-python/Sphinx[${PYTHON_USEDEP}] )
	sentry? ( dev-python/raven[${PYTHON_USEDEP}] )
	sentry-sdk? ( dev-python/sentry-sdk[${PYTHON_USEDEP}] )
	tests? ( dev-python/flask-login[${PYTHON_USEDEP}] )
	tests? ( dev-python/httpretty[${PYTHON_USEDEP}] )
	tests? ( dev-python/mock[${PYTHON_USEDEP}] )
	tests? ( dev-python/pytest-invenio[${PYTHON_USEDEP}] )
	tests? ( dev-python/iniconfig[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
