# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="TikTok Live Python Client"

HOMEPAGE="https://github.com/isaackogan/TikTokLive"
LICENSE="MIT"
SRC_URI="https://files.pythonhosted.org/packages/ac/42/c48817270a680afb5408395e3594f300b5def531b34fea87b51b9ee32ce8/tiktoklive-${REALVERSION}.tar.gz"
SOURCEFILE="tiktoklive-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=">=dev-python/httpx-0.25.0[${PYTHON_USEDEP}]
	dev-python/pyee[${PYTHON_USEDEP}]
	dev-python/ffmpy[${PYTHON_USEDEP}]
	dev-python/websockets-proxy[${PYTHON_USEDEP}]
	dev-python/betterproto[${PYTHON_USEDEP}]
	>=dev-python/async-timeout-4.0.3[${PYTHON_USEDEP}]
	dev-python/mashumaro[${PYTHON_USEDEP}]
	dev-python/protobuf3-to-dict[${PYTHON_USEDEP}]
	dev-python/protobuf[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
