# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_11,3_12,3_13,3_14} )
DISTUTILS_USE_PEP517=wheel

inherit python-r1 gs-pypi

DESCRIPTION="TF-Agents: A Reinforcement Learning Library for TensorFlow [wheel]"

HOMEPAGE="https://github.com/tensorflow/agents"
LICENSE="Apache-2.0"
SRC_URI="https://files.pythonhosted.org/packages/py3/${REALNAME::1}/${REALNAME}/${REALNAME//-/_}-${REALVERSION}-py3-none-any.whl"
SOURCEFILE="${REALNAME//-/_}-${REALVERSION}-py3-none-any.whl"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="reverb tests"
DEPENDENCIES=">=dev-python/absl-py-0.6.1[${PYTHON_USEDEP}]
	>=dev-python/cloudpickle-1.3[${PYTHON_USEDEP}]
	dev-python/gin-config[${PYTHON_USEDEP}]
	dev-python/gym[${PYTHON_USEDEP}]
	>=dev-python/numpy-1.19.0[${PYTHON_USEDEP}]
	dev-python/pillow[${PYTHON_USEDEP}]
	>=dev-python/six-1.10.0[${PYTHON_USEDEP}]
	>=dev-python/protobuf-3.11.3[${PYTHON_USEDEP}]
	>=dev-python/wrapt-1.11.1[${PYTHON_USEDEP}]
	~dev-python/typing-extensions-4.5.0[${PYTHON_USEDEP}]
	~dev-python/pygame-2.1.3[${PYTHON_USEDEP}]
	dev-python/tensorflow-probability[${PYTHON_USEDEP}]
	reverb? ( dev-python/rlds[${PYTHON_USEDEP}] )
	reverb? ( dev-python/dm-reverb[${PYTHON_USEDEP}] )
	reverb? ( dev-python/tensorflow[${PYTHON_USEDEP}] )
	tests? ( >=dev-python/mock-2.0.0[${PYTHON_USEDEP}] )
	tests? ( dev-python/opencv-python[${PYTHON_USEDEP}] )
	tests? ( dev-python/pybullet[${PYTHON_USEDEP}] )
	tests? ( >=dev-python/scipy-1.1.0[${PYTHON_USEDEP}] )
	virtual/allow-pypi-wheels"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
