# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_12,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="An AsyncIO API for controlling the Drayton Wiser Heating system"

HOMEPAGE="https://github.com/msp1974/aioWiserHeatAPI"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/52/66/c4ff4df0a4d1448c36d4091282622f0cbc55eb8b84f18d8e222b6dd1e418/aiowiserheatapi-${REALVERSION}.tar.gz"
SOURCEFILE="aiowiserheatapi-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES=">=dev-python/zeroconf-0.131.0[${PYTHON_USEDEP}]
	>=dev-python/aiohttp-3.9.3[${PYTHON_USEDEP}]
	>=dev-python/aiofiles-23.2.1[${PYTHON_USEDEP}]
	>=dev-python/pyyaml-6.0.1[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
