# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="${PN}"
LITERALNAME="${PN}"
REALVERSION="${PV}"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_10,3_11,3_12} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="Supermarq is a scalable, application-centric quantum benchmarking suite."

HOMEPAGE="https://github.com/Infleqtion/client-superstaq"
LICENSE="Apache-2.0"
SRC_URI="https://files.pythonhosted.org/packages/68/48/2ba4ab2d45645a1ac57894e3b9ad16506ff635bb26148d9950f6c79314a7/supermarq-${REALVERSION}.tar.gz"
SOURCEFILE="supermarq-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="dev"
DEPENDENCIES="dev-python/cirq-superstaq[${PYTHON_USEDEP}]
	dev-python/qiskit-superstaq[${PYTHON_USEDEP}]
	>=dev-python/scikit-learn-1.0[${PYTHON_USEDEP}]
	dev? ( dev-python/checks-superstaq[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
